### ISSUE TITLE
Assertion failure in 'frontend'

### ISSUE THREAD

**Issue by fabsx00** [rose-compiler/rose#10]
Hi,
I'm currently trying to link code originally written for rose-edg4x against the code in this repository and I'm encountering a strange problem. I've narrowed the code down to this short snippet:

```
#include <rose.h>

class MyProcessor
{public:
    MemoryMap memoryMap;
    virtual ~MyProcessor();
};
MyProcessor :: ~MyProcessor() { }

int main(int argc, char *argv[]) {
    SgProject* myProject = frontend(argc, argv);
}
```

When I compile and run the code against different x86 ELF binaries, I get the following assertion failure:

```
... /rose/include/rose/Sawyer/SharedPointer.h:363: static size_t Sawyer::SharedPointer<T>::releaseOwnership(Sawyer::SharedPointer<T>::Pointee*) [with T = Sawyer::Container::Buffer<long unsigned int, unsigned char>; size_t = long unsigned int; Sawyer::SharedPointer<T>::Pointee = Sawyer::Container::Buffer<long unsigned int, unsigned char>]: Assertion `rawPtr->SharedObject::nrefs_ > 0' failed.
Aborted
```

Running gdb shows that this happens inside 'frontend'. However, when I change the code to

```
#include <rose.h>

class MyProcessor
{public:
    MemoryMap memoryMap;
    virtual ~MyProcessor() { }
};

int main(int argc, char *argv[]) {
    SgProject* myProject = frontend(argc, argv);
}
```

the analysis runs fine. Any ideas?

**Comment by matzke1** [comment]
The MemoryMap API has changed somewhat since you reported this, so I'm closing this old issue. If you're still having a problem please create a new issue with updated example code. Thanks.
