### ISSUE TITLE
Failed to set type for template argument

### ISSUE THREAD

**Issue by gary-bai** [rose-compiler/rose#101]
Reproducer:
```cpp
template<int I>
class A {
  int a[I];
};

template <typename T>
class stream {
  T data;
};

void top() {
  stream<A<10> > data;
}
```
Partial AST dump:
```
SgTemplateInstantiationDecl:template<> class stream< A< 10 > > {private: class A< 10 > data;};
SgTemplateInstantiationDefn:template<> class stream< A< 10 > > {private: class A< 10 > data;}
```
For that instantiated class, with the intention of changing its template type argument `A<10>` to an already existed different C struct `A_10` via the following method:
```
SgTemplateArgument::set_type(SgType *type)
```
However, the expected result does not happen.

Affected version: rose-0.10.0.30

**Comment by tristanvdb** [comment]
Hi,

You will have to find or create an instantiation `stream<A_10>` then set the type of `data` in `top`. You can find an example at https://github.com/LLNL/typeforge/blob/master/lib/TFTypeTransformer.cpp#L196 which deals with changing the template argument for std::vector.

Thanks,
-Tristan
