### ISSUE TITLE
invalid type conversion

### ISSUE THREAD

**Issue by seanchen1002** [rose-compiler/rose#106]
Hi, when I try to compile the following code.
` #include <emmintrin.h>
   void top() {
     __m128i val;
  __m128i next = _mm_insert_epi16(val, 10, 7);
   }
`
I met invalid type conversion error
`"/pool/local/youxiang/merlin_benchmark/xfopencv/examples_sdaccel/boundingbox/xi
          linx_mo/t.c", line 4: error: invalid type conversion
  __m128i next = _mm_insert_epi16(val, 10, 7);
                 ^

Errors in Processing Input File: throwing an instance of "frontend_failed" exception due to syntax errors detected in the input code
`
version: 0.10.0.30 

Thanks
-Sean

**Comment by gary-bai** [comment]
https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_insert_epi16&expand=3139

**Comment by tristanvdb** [comment]
https://github.com/rose-compiler/rose/issues/136
