### ISSUE TITLE
ROSE frontend will crash when multiple input files include <complex>

### ISSUE THREAD

**Issue by seanchen1002** [rose-compiler/rose#120]
//t1.cpp
`#include <complex>`
//t2.cpp
`#include <complex>`

[youxiang@merlin4 build]$ /local/youxiang/install/bin/rose-c++ t1.cpp t2.cpp
insertModifierTypeIntoTypeTable(): result is modifier type to base_type = 0x7f83fd7ef268 = SgTypeComplex name = CComplex
t      = 0x7f83fd9aad50 = SgModifierType
result = 0x7f83fd9e29b0 = SgModifierType
t_stripped           = 0x7f83fd7ef100 = SgTypeComplex
result_stripped      = 0x7f83fd7ef268 = SgTypeComplex
t_name      = CComplex
result_name = CComplex
t_isTypeEquivalent          = false
t_stripped_isTypeEquivalent = false
rose-c++: Cxx_Grammar.C:71483: static SgModifierType* SgModifierType::insertModifierTypeIntoTypeTable(SgModifierType*): Assertion `t->stripType() == result->stripType()' failed.
Aborted

**Comment by tristanvdb** [comment]
Forgot to close that issue after fixing.
-Tristan
