### ISSUE TITLE
unable to compile from source

### ISSUE THREAD

**Issue by Brice-D** [rose-compiler/rose#134]
i am installing rose-compiler from source.
but the following commands don't work:

**make core -j${NUM_PROCESSORS}
**make install-core -j${NUM_PROCESSORS}
**make check-core -j${NUM_PROCESSORS}

i have run the commands from "${ROSE_HOME}/build" directory how shown in the picture.

![error-rose](https://user-images.githubusercontent.com/24481556/97306723-25332280-185f-11eb-86cf-aca6c088d3c5.PNG)

i get the error "make: *** No rule to make target 'core' (Or install-core Or check-core).  Stop."  for all this commands.
how can i solve this issues.?

**Comment by pinnown** [comment]
This looks like either the build or configure steps failed. Check to make sure there is a Makefile in the build directory. 

Try rerunning the build and configure commands, they should both have a message at the end saying they completed successfully.

**Comment by Brice-D** [comment]
i get this result from build (picture 1) and configure  (picture 1 and 2). 

![build](https://user-images.githubusercontent.com/24481556/97351064-8ecc2480-1891-11eb-8c76-98f84319999c.PNG)

![configure1](https://user-images.githubusercontent.com/24481556/97351095-97245f80-1891-11eb-9184-a4faa3e492d6.PNG)

![configure2](https://user-images.githubusercontent.com/24481556/97351118-9db2d700-1891-11eb-9148-6abffa8f0325.PNG)

do i have to disable this config about blacklist? gut idea or how can i solve this issue?

**Comment by pinnown** [comment]
If you don't need binary analysis then you can either us "--disable-blacklist" and it should build but the binary analysis parts will not work correctly. The other thing you can do is remove binaries from the list on enabled languages.

If you need binary analysis you will need to build a new boost version, I would recommend 1.69.0 or 1.72.0.

**Comment by Brice-D** [comment]
thanks a lot. i just remove "binaries". i hope that, i would not need it later.
