### ISSUE TITLE
error 404

### ISSUE THREAD

**Issue by Brice-D** [rose-compiler/rose#138]
hi, this links for downloading GCC is no more accessible. I get error 404. please update the link

https://bigsearcher.com/mirrors/gcc/releases/gcc-7.4.0/gcc-7.4.0.tar.bz2

**Comment by pinnown** [comment]
The link has been updated to ftp://ftp.gnu.org/gnu/gcc/gcc-7.4.0/gcc-7.4.0.tar.gz
