### ISSUE TITLE
make error: librose.so: undefined reference to ...

### ISSUE THREAD

**Issue by king-mahdi** [rose-compiler/rose#14]
I am getting following error while running make:

make[3]: Entering directory '/usr/local/rose_build/src'
  CXX      dummyCppFileForLibrose.lo
  CXX      rose_config-rose-config.o
  CXX      testRoseLib.o
  CXXLD    librose.la
  CXXLD    rose-config
  CXXLD    testSharedRoseLib
/usr/local/rose_build/src/.libs/librose.so: undefined reference to `StringUtility::stripPathFromFileName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/local/rose_build/src/.libs/librose.so: undefined reference to `StringUtility::numberToString[abi:cxx11](void const*)'
/usr/local/rose_build/src/.libs/librose.so: undefined reference to `StringUtility::numberToString[abi:cxx11](long long)'
/usr/local/rose_build/src/.libs/librose.so: undefined reference to `StringUtility::numberToString[abi:cxx11](int)'
collect2: error: ld returned 1 exit status
Makefile:1758: recipe for target 'testSharedRoseLib' failed
make[3]: *** [testSharedRoseLib] Error 1
make[3]: *** Waiting for unfinished jobs....
/usr/local/rose_build/src/.libs/librose.so: undefined reference to `StringUtility::stripPathFromFileName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/local/rose_build/src/.libs/librose.so: undefined reference to `StringUtility::numberToString[abi:cxx11](void const*)'
/usr/local/rose_build/src/.libs/librose.so: undefined reference to `StringUtility::numberToString[abi:cxx11](long long)'
/usr/local/rose_build/src/.libs/librose.so: undefined reference to `StringUtility::numberToString[abi:cxx11](int)'
collect2: error: ld returned 1 exit status
Makefile:1754: recipe for target 'rose-config' failed
make[3]: *** [rose-config] Error 1
make[3]: Leaving directory '/usr/local/rose_build/src'
Makefile:1816: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/usr/local/rose_build/src'
Makefile:1624: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/usr/local/rose_build'
Makefile:1486: recipe for target 'all' failed
make: *** [all] Error 2

Has anyone had simlar issue?

My configuration:

OS: Ubuntu 16.04
GCC: 5.4 (default on Ubuntu 16.04)
Boost: 1.52
Java: 1.8

I realize this is not close to what is Rose gets tested for, however, I have also had problems with building with gcc 4.8 on Ubuntu 14.04, Java 1.7 and Boost 1.50 (same issue as current one on same machine).

I should also mention that since the binary for EDG version that is requested by rose MakeFile is not avaialble, I download one of the latest ones available and rename it to the one that is request, put it on src/frontend/CxxFrontend, then run make while disconnecting machine from internet. 

This EDG version is requested: roseBinaryEDG-4-9-x86_64-pc-linux-gnu-gnu-5.4-4.509d2b08bc274a69f35861c342ccce0c910dc4e1.tar.gz
I downloaded this one: roseBinaryEDG-4-9-x86_64-pc-linux-gnu-gnu-5.3-4.fa1b6bbcf0f8207a9014f2ba3d0c5774603edac8.tar.gz

Can this be the source of the issue?

**Comment by dark0venom** [comment]
I have similar issue.... I had a previous issue a exact place by forgetting all when building boost 1.61 from source. Pretty sure is dependency problem or maybe your right with the EDM. Iam on Debian. Searched the internet and found that only thread......

**Comment by charlesareynolds** [comment]
All,
Are you able to use ubuntu 18.04?  If so, we have a binary install instructions at https://github.com/rose-compiler/rose/wiki/Install-Using-apt-get and source install instructions at https://github.com/rose-compiler/rose/wiki/Installation-on-Ubuntu-From-Source.

**Comment by charlesareynolds** [comment]
We will close this issue since there has been no response to the last comment and no other activity since 2018/01, and there is a solution (ubuntu 18.04).
