### ISSUE TITLE
please mention a working gcc/clang/boost configuration

### ISSUE THREAD

**Issue by tobias-loew** [rose-compiler/rose#15]
It would be great if the readme (or some build_readme) file could contain the specs of a working build environment, since the hints in the docs are sometimes misleading and I had to add "stdc++" to the linker input in several projects (using gcc-4.8 and automake)
Thanks for the great work!
Tobias

**Comment by pinnown** [comment]
Some information about configurations can be found at https://github.com/rose-compiler/rose/wiki/Supported-Configurations and results from testing can be found at matrix.rosecompiler.org.
