### ISSUE TITLE
[Question] Does deepCopy also clone the symbol table when called on a defining SgFunctionDeclaration node?

### ISSUE THREAD

**Issue by forflo** [rose-compiler/rose#154]
Steps that led me to my question:

- Clone a function O using `SageInterface::deepCopy` producing function C.
- Rename the function C (and all its non-defining declarations) to make the AST valid again.
- Do `SageInterface::deepDelete(O->get_definition()->get_body())
- Do `auto bb = SageBuilder::buildBasicBlock();`
- Do `O->get_definition()->set_body(bb);`
- Do `bb->set_parent(O->get_definition());`

Later, the Unparser uses the wrong `SgNames` during unparsing of function O. This leads me to the assumption that both function declarations O and C share the same Symbol table.

- Is this desired behavior?
- Is there another facility for cloning SgScopeStatement nodes which __does__ clone Symbol table as well?

**Comment by tristanvdb** [comment]
Hi,

Sorry for the late reply, that is the expected behavior for deepcopy as it copies the tree with all other edge intact. The transformation you are describing would have to either be extremelly limited in scope (and nearly useless) or extremelly complex to handle any situation.

Thanks,
-Tristan
