### ISSUE TITLE
Convert C to Fortran with rose.

### ISSUE THREAD

**Issue by hongyi-zhao** [rose-compiler/rose#156]
Hi,

I'm very glad to know this project. I want to know if I can convert a project written in C to FORTRAN with rose. Any hints will be highly appreciated.

Regards,
HY

**Comment by peihunglin** [comment]
You should be able to build a C to Fortran translator using ROSE. 
You can reference a project Fortran_to_C to learn about how to build a language translator:  https://github.com/rose-compiler/rose/tree/weekly/projects/Fortran_to_C.
