### ISSUE TITLE
All Rose Binary Analysis tools are not installed

### ISSUE THREAD

**Issue by zain-CSsol** [rose-compiler/rose#167]
Hello I am trying to use specific rose binary analysis tool "bat-cg" but it is not available infect not this but many other tools mentioned [here](https://github.com/rose-compiler/rose/wiki/ROSE-based-tools) are not present. I tried first on Ubuntu 20.04 with apt-get method listed [here](https://github.com/rose-compiler/rose/wiki/Install-Using-apt-get) and then also give it a try by building from source mentioned [here](https://github.com/rose-compiler/rose/wiki/Installation-on-Ubuntu-From-Source). There were many errors during source build but it did not aborted the compile so i assume it may have been installed correctly . Following are my machine specifications

- Ubuntu 20.04 OS using WSL on Windows 10
- Intel Core i5 HP
- 16 GB of RAM
- SD Drive

For confirmation i ran the command to check what is installed by typing the following command

`dpkg -L rose rose-tools | grep /usr/bin/`

The Complete output is following which clearly shows all rose tools are not installed only few of these are available

/usr/bin/edgcpdisp
/usr/bin/rose-c++
/usr/bin/rose-cc
/usr/bin/rose-compiler
/usr/bin/rose-config
/usr/bin/runRoseUtil
/usr/bin/stringify-enums
/usr/bin/ArrayProcessor
/usr/bin/KeepGoingTranslator
/usr/bin/astCopyReplTest
/usr/bin/astRewriteExample1
/usr/bin/autoPar
/usr/bin/autoTuning
**/usr/bin/bat-ana
/usr/bin/bat-cc
/usr/bin/bat-cfg
/usr/bin/bat-container
/usr/bin/bat-dis
/usr/bin/bat-entropy
/usr/bin/bat-insnfreq
/usr/bin/bat-insnfreq-cmp
/usr/bin/bat-linear
/usr/bin/bat-lsb
/usr/bin/bat-lsf
/usr/bin/bat-mem
/usr/bin/bat-prop
/usr/bin/bat-stack-deltas
/usr/bin/bat-trace**
/usr/bin/checkFortranInterfaces
/usr/bin/classMemberVariablesInLambdas
/usr/bin/codeInstrumentor
/usr/bin/compassEmptyMain
/usr/bin/compassMain
/usr/bin/compassVerifier
/usr/bin/defaultTranslator
/usr/bin/dotGenerator
/usr/bin/dotGeneratorWholeASTGraph
/usr/bin/extractMPISkeleton
/usr/bin/featureVector
/usr/bin/fileInfoDumper
/usr/bin/generateSignatures
/usr/bin/globalVariablesInLambdas
/usr/bin/identityTranslator
/usr/bin/inlineEverything
/usr/bin/mangledNameDumper
/usr/bin/measureTool
/usr/bin/moveDeclarationToInnermostScope
/usr/bin/outline
/usr/bin/pdfGenerator
/usr/bin/preprocessingInfoDumper
/usr/bin/qualifiedNameDumper
/usr/bin/rajaChecker
/usr/bin/roseupcc
/usr/bin/sampleCompassSubset
/usr/bin/simpleTraversal
/usr/bin/summarizeSignatures
/usr/bin/textASTGenerator

The tools in bold shows the available ones

**Comment by matzke1** [comment]
You have to enable binary analysis when you configure ROSE. If you're using GNU Autotools, the switch is "--enable-languages" and its value needs to include the word "binaries".

**Comment by zain-CSsol** [comment]
> You have to enable binary analysis when you configure ROSE. If you're using GNU Autotools, the switch is "--enable-languages" and its value needs to include the word "binaries".

Could you please elaborate in detail, do i need to recompile rose again? or do i need to invoke rose-config ? also write down complete command

**Comment by zain-CSsol** [comment]
thanks it helped a lot .
