### ISSUE TITLE
git clone failed: ssh: Could not resolve hostname rosecompiler2.llnl.gov: Name or service not known fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by infojg9** [rose-compiler/rose#168]
Dear Rose Maintainer Team,

just tried to clone the mainline head and have two questions:

Q1. faced access error, any idea how to resolve it ?

Q2. Is it https://github.com/rose-compiler/rose/releases/tag/v0.11.34.1 more stable compared to mainline ? It looks like also still broken ?

Q1.
`
$ git clone -v --recurse-submodules git@github.com:rose-compiler/rose.git
Cloning into 'rose'...
agent key RSA SHA256:qM52XGY+Pq7Yn1RX59FHK9fqCfTrBOwW0kWeTAy667A returned incorrect signature type
remote: Enumerating objects: 384443, done.
remote: Counting objects: 100% (8348/8348), done.
remote: Compressing objects: 100% (2641/2641), done.
remote: Total 384443 (delta 5420), reused 8343 (delta 5416), pack-reused 376095
Receiving objects: 100% (384443/384443), 426.98 MiB | 5.79 MiB/s, done.
Resolving deltas: 100% (289637/289637), done.
Updating files: 100% (32945/32945), done.
Submodule 'projects/vulnerabilitySeeding' (ssh://git@rosecompiler2.llnl.gov:10022/rose-compiler/vulnerability-seeding.git) registered for path 'projects/vulnerabilitySeeding'
Submodule 'src/frontend/CxxFrontend/EDG' (ssh://git@rosecompiler2.llnl.gov:10022/rose-compiler/edg.git) registered for path 'src/frontend/CxxFrontend/EDG'

Cloning into '/home/user1/PycharmProjects/eims/cert/rose/projects/vulnerabilitySeeding'...
ssh: Could not resolve hostname rosecompiler2.llnl.gov: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'ssh://git@rosecompiler2.llnl.gov:10022/rose-compiler/vulnerability-seeding.git' into submodule path '/home/user1/PycharmProjects/eims/cert/rose/projects/vulnerabilitySeeding' failed
Failed to clone 'projects/vulnerabilitySeeding'. Retry scheduled
Cloning into '/home/user1/PycharmProjects/eims/cert/rose/src/frontend/CxxFrontend/EDG'...
ssh: Could not resolve hostname rosecompiler2.llnl.gov: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'ssh://git@rosecompiler2.llnl.gov:10022/rose-compiler/edg.git' into submodule path '/home/user1/PycharmProjects/eims/cert/rose/src/frontend/CxxFrontend/EDG' failed
Failed to clone 'src/frontend/CxxFrontend/EDG'. Retry scheduled

Cloning into '/home/user1/PycharmProjects/eims/cert/rose/projects/vulnerabilitySeeding'...
ssh: Could not resolve hostname rosecompiler2.llnl.gov: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'ssh://git@rosecompiler2.llnl.gov:10022/rose-compiler/vulnerability-seeding.git' into submodule path '/home/user1/PycharmProjects/eims/cert/rose/projects/vulnerabilitySeeding' failed
Failed to clone 'projects/vulnerabilitySeeding' a second time, aborting

`

Q2.

`
$ git clone --branch v0.11.34.1 -v --recurse-submodules git@github.com:rose-compiler/rose.git
Cloning into 'rose'...
agent key RSA SHA256:qM52XGY+Pq7Yn1RX59FHK9fqCfTrBOwW0kWeTAy667A returned incorrect signature type
remote: Enumerating objects: 384443, done.
remote: Counting objects: 100% (8348/8348), done.
remote: Compressing objects: 100% (2641/2641), done.
remote: Total 384443 (delta 5420), reused 8343 (delta 5416), pack-reused 376095
Receiving objects: 100% (384443/384443), 426.98 MiB | 4.36 MiB/s, done.
Resolving deltas: 100% (289637/289637), done.
Note: switching to 'b7b8d7b8de6851b89310f9ba97483d8da09617f1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

Updating files: 100% (32945/32945), done.
Submodule 'projects/vulnerabilitySeeding' (ssh://git@rosecompiler2.llnl.gov:10022/rose-compiler/vulnerability-seeding.git) registered for path 'projects/vulnerabilitySeeding'
Submodule 'src/frontend/CxxFrontend/EDG' (ssh://git@rosecompiler2.llnl.gov:10022/rose-compiler/edg.git) registered for path 'src/frontend/CxxFrontend/EDG'
Cloning into '/home/user1/PycharmProjects/eims/cert/rose/projects/vulnerabilitySeeding'...
ssh: Could not resolve hostname rosecompiler2.llnl.gov: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'ssh://git@rosecompiler2.llnl.gov:10022/rose-compiler/vulnerability-seeding.git' into submodule path '/home/user1/PycharmProjects/eims/cert/rose/projects/vulnerabilitySeeding' failed
Failed to clone 'projects/vulnerabilitySeeding'. Retry scheduled
Cloning into '/home/user1/PycharmProjects/eims/cert/rose/src/frontend/CxxFrontend/EDG'...
ssh: Could not resolve hostname rosecompiler2.llnl.gov: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'ssh://git@rosecompiler2.llnl.gov:10022/rose-compiler/edg.git' into submodule path '/home/user1/PycharmProjects/eims/cert/rose/src/frontend/CxxFrontend/EDG' failed
Failed to clone 'src/frontend/CxxFrontend/EDG'. Retry scheduled
Cloning into '/home/user1/PycharmProjects/eims/cert/rose/projects/vulnerabilitySeeding'...
ssh: Could not resolve hostname rosecompiler2.llnl.gov: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'ssh://git@rosecompiler2.llnl.gov:10022/rose-compiler/vulnerability-seeding.git' into submodule path '/home/user1/PycharmProjects/eims/cert/rose/projects/vulnerabilitySeeding' failed
Failed to clone 'projects/vulnerabilitySeeding' a second time, aborting
user1@localhost 1000 ~/PycharmProjects/eims/cert [Tue May 25  6:36:10] 
`

Best Regards
infojg9

**Comment by pinnown** [comment]
You need to remove the flag "--recurse-submodules". The sub modules contain 3rd party licensed code that we can not distribute open source. When the sub modules are not present the build process will download a binary version of the 3rd party libraries if needed.

**Comment by milahu** [comment]
> The sub modules contain 3rd party licensed code that we can not distribute open source.

can we fetch these private sources in cmakelists.txt?
would be nice to fix `git --recurse-submodules` for normal users
