### ISSUE TITLE
macOS i386 configure error

### ISSUE THREAD

**Issue by jayvdb** [rose-compiler/rose#170]
During configure on macos BigSur with Apple LLVM version 12.0.5 (clang-1205.0.22.9) I see .
```
Checking binary analysis
ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd (3 slices)
ld: dynamic main executables must link with libSystem.dylib for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
The `error` is coded red, but the configure seems to proceed ok anyway.

**Comment by peihunglin** [comment]
Together with the #169, we need to know a bit more how you plan to use ROSE on Mac OS.  Do you plan to use any specific language or binary analysis support?
Binary analysis feature is not tested on Mac, we suggest using Linux for binary analysis support.

**Comment by jayvdb** [comment]
Given I didn't get ROSE to compile for my system, I do not plan to use ROSE at all.

./configure shouldnt emit clang errors.  They should be in config.log, and summarised in the ./configure output.

**Comment by peihunglin** [comment]
We would suggest specifying desired language support for ROSE using "--enable-languages=".   As binary support is not part of our Mac system testing, we suggest using Linux system for the binary support.
