### ISSUE TITLE
Compass files that probably should be added to the install using apt get

### ISSUE THREAD

**Issue by DLightstone** [rose-compiler/rose#173]
The following files might be useful to a user (that does not build from source)

(1) The Compass user manual (which can be prepared from source)
(2) An example Compass tool selection (projects\compass\tools\compass\RULE_SELECTION.in)
(3) An example compass_parameters

**Comment by DLightstone** [comment]
see closure notification for #174

**Comment by tristanvdb** [comment]
Compass and qtWidgets are no longer supported and will be removed from the ROSE repository in the future. We may create a separate repo for these kinds of unsupported legacy tools, and they'll of course continue to be available as old commits in the ROSE repo.
