### ISSUE TITLE
Dealing multiple Files

### ISSUE THREAD

**Issue by qifengpan** [rose-compiler/rose#178]
Firstly, thanks for this amazing tool! it helps a lot in my research.
I'm currently developing a transformation project with Fortran90 code. A simple transformation code is now working fine with few files ,in case they don't have too strong dependence with each other. For large program with multiple files and strong file dependence, it is quite struggling to use this transformation code.

I read in tutorial there is a file called astFileIO_ReadMultipleASTs.C which shows a functionnality that we could read the file one by one and then parse them separately. However the AST merging part is missing. I guess it would be the solution for multiple file parsing, and i want to ask some questions for that:

 Is there any exsisting method which would merge all AST together?

if there is not, would then mean i need to specifiy the dependence by myself. I would be appreciate if there are some demo code show us how to do that.

**Comment by tristanvdb** [comment]
Hi,

I am sorry for the late reply. Please see the response to [issue 153](https://github.com/rose-compiler/rose/issues/153).

Thanks,
-Tristan
