### ISSUE TITLE
Emit C code using ROSE?

### ISSUE THREAD

**Issue by SamuelMarks** [rose-compiler/rose#187]
In Python I can do this:
```py
class_reduction_v2 = ClassDef(
    name="ReductionV2",
    bases=[],
    keywords=[],
    body=[
        Expr(value=set_value("foo")),
        Assign(targets=[Name(id="AUTO", ctx=Store())], value=set_value("auto")),
        Assign(targets=[Name(id="NONE", ctx=Store())], value=set_value("none")),
        Assign(targets=[Name(id="SUM", ctx=Store())], value=set_value("sum")),
        Assign(
            targets=[Name(id="SUM_OVER_BATCH_SIZE", ctx=Store())],
            value=set_value("sum_over_batch_size"),
        ),
    ],
    decorator_list=[],
)
```

Which produces:
```py
class ReductionV2:
    """ foo """
    AUTO = 'auto'
    NONE = 'none'
    SUM = 'sum'
    SUM_OVER_BATCH_SIZE = 'sum_over_batch_size'
```

Looks like neither LLVM LibTooling nor LLVM libclang have support for this:
https://discourse.llvm.org/t/create-and-emit-ast-for-struct-clang-recorddecl/61383

Is this something I can do with ROSE?

**Comment by chunhualiao** [comment]
ROSE is designed to develop source-to-source analysis and transformation tools. You can develop a ROSE-based tool to generate C/C++/Fortran code. 

Here is an example to build a source file from scratch and fill in more content: 

https://github.com/rose-compiler/rose/blob/weekly/tests/nonsmoke/functional/roseTests/astInterfaceTests/buildFile.C 

More general How-tos are available: 

https://github.com/rose-compiler/rose/wiki/Developing-ROSE-based-Tools
https://en.wikibooks.org/wiki/ROSE_Compiler_Framework/How-tos

**Comment by SamuelMarks** [comment]
@chunhualiao Oh wow that has [alomst] everything I want http://rosecompiler.org/ROSE_HTML_Reference/namespaceSageBuilder.html

FYI: Your `buildFile.c` should be `buildFile.cpp` (or other valid C++ file extension).

Thanks looks super useful

---

On a related note, I was working on a scanner, parser, and pretty printer of my own (in pure C89)… with novelty of zero dependencies, cross-platform, and macro support.

Is there any way to parser, generate and emit—without evaluation—the preprocessor language of C, using ROSE?

**Comment by SamuelMarks** [comment]
@chunhualiao Oh wow that has [almost] everything I want http://rosecompiler.org/ROSE_HTML_Reference/namespaceSageBuilder.html

FYI: Your `buildFile.c` should be `buildFile.cpp` (or other valid C++ file extension).

Thanks looks super useful

---

On a related note, I was working on a scanner, parser, and pretty printer of my own (in pure C89)… with novelty of zero dependencies, cross-platform, and macro support.

Is there any way to parser, generate and emit—without evaluation—the preprocessor language of C, using ROSE?

**Comment by chunhualiao** [comment]
> @chunhualiao Oh wow that has [almost] everything I want http://rosecompiler.org/ROSE_HTML_Reference/namespaceSageBuilder.html
> 
> FYI: Your `buildFile.c` should be `buildFile.cpp` (or other valid C++ file extension).

.C is a valid C++ file extension.  See Filename of Infobox  of https://en.wikipedia.org/wiki/C%2B%2B . 
 
> Thanks looks super useful
> 
> On a related note, I was working on a scanner, parser, and pretty printer of my own (in pure C89)… with novelty of zero dependencies, cross-platform, and macro support.
> 
> Is there any way to parser, generate and emit—without evaluation—the preprocessor language of C, using ROSE?

ROSE does support the processing of preprocessing information: 
https://en.wikibooks.org/wiki/ROSE_Compiler_Framework/FAQ#How_to_handle_#include_%22header.h%22,_#if,_#define_etc._?

**Comment by SamuelMarks** [comment]
RE: file-extension, oh it must just be GitHub not highlighting as it doesn't recognise that.

Thanks that solves my issues =)

PS: Might still work on my own scanner, parser, and pretty printer as it's pure C and has no dependencies so can trivially be cross-platform and distributed to others (with tiny built time + binary size).
