### ISSUE TITLE
Rose Fortran unparsing ALL variables within a Module with PUBLIC attribute

### ISSUE THREAD

**Issue by thiagotei** [rose-compiler/rose#19]
The variables created by the [buildVariableDeclaration](https://github.com/thiagotei/rose/blob/master/src/frontend/SageIII/sageInterface/sageBuilder.C#L1200) if created  inside a module are unparsed with a PUBLIC attribute.

However, the PUBLIC attribute can only appear in module variables, procedure, derived type, named constant, or nameless group. It cannot happen with subroutine variables, for instance, that are inside a module.

The problem[ starts in the backend](https://github.com/thiagotei/rose/blob/master/src/backend/unparser/FortranCodeGeneration/unparseFortran_statements.C#L3915). And [the bug is here](https://github.com/thiagotei/rose/blob/master/src/roseSupport/transformationSupport.C#L2648), where it just looks if the variable is in inside a module, but not if the variable is a module variable.

**Comment by peihunglin** [comment]
The default Fortran access attribute has been changed to "undefined" in the [development branch ](https://github.com/rose-compiler/rose/tree/develop).  Therefore the "PUBLIC" will not be unparsed by default.  [Test example](https://github.com/rose-compiler/rose/blob/96c1f648f44ff4a74e4bc54204d0a1afcedafaaa/tests/nonsmoke/functional/CompileTests/Fortran_tests/test2019_accessibility_attribute2.f90) was tested and unparsed without problem.  This ticket will be closed.  Please provide more test cases and reopen issue if the issue still exists.
