### ISSUE TITLE
Windows Build/Dist Support

### ISSUE THREAD

**Issue by SaifRushdHadad** [rose-compiler/rose#191]
What is LLNL's roadmap to support distributing ROSE on Windows?
The CMake build system is very promising and the existing build system is relatively complex in comparison to use.

There are no EDG binaries available for download for: MSVC, Clang-cl/Clang cross compiling, Clang, and/or Mingw-GXX.
The CMake buildsystem does not have a way to select usage of Clang-frontend instead of EDG, so it cannot progress, but does have some references to MSVC toolchain.

**Comment by pinnown** [comment]
There is currently no plan to support distribution on Windows. The best option right now for running ROSE on Windows is to use Windows Subsystem for Linux.

The CMake and Clang support are both being upgraded right now and the work should be completed in the next year. These efforts may help support Windows but it in not a current objective.
