### ISSUE TITLE
ROSE c++: Problem with precedence in AstFromString.

### ISSUE THREAD

**Issue by ranjanvittal** [rose-compiler/rose#20]
Bitwise and operator (&) has a higher priority than the logical and (&&) operator. This makes it impossible for AstFromString to parse any logical and expression as & is also a unary operator.
Consider a case (a && b) which we are converting from string to expression. This gets converted
to (a & &b) as Bitwise and operator and the unary & both have higher precedence than logical and (&&). The biwise or operator (|) also has a a higher priority than logical or (||) though this does not
have any conflict due to the fact that | is not a unary operator.

The solution is to correct the precedence order.

**Comment by tristanvdb** [comment]
I filled this as a bug in our Jira. As the issue is old, I will close it immediately.
