### ISSUE TITLE
Mentions of C98 standard, is this a typo?

### ISSUE THREAD

**Issue by tweska** [rose-compiler/rose#222]
On Github the about text mentions a C98 standard, some comments in the code also mention this mysterious standard.

I cannot find anything about a C98 standard so I am guessing someone just got confused with the C++98, C89 and C99 standards.

This is not a huge issue but maybe a nice "good first issue". :^)

**Comment by lara** [comment]
C98 is another informal name (just like C99) for the ISO/IEC 9899:1999 standard. 

It would be nice if the project used C99 as that is more commonly used in the industry, but referring to it as C98 is not necessarily wrong.

**Comment by tristanvdb** [comment]
This is fixed
