### ISSUE TITLE
EDG Download Error for Aarch64

### ISSUE THREAD

**Issue by zzhang77** [rose-compiler/rose#224]
gcc version: 8.3.1
Environment: CentOS7.9, AARCH64
It failed with EDG binary error like the case [#23 ](https://github.com/rose-compiler/rose/issues/23) when I tried to make core. So I followed [EDG-Installation-Instructions](https://github.com/rose-compiler/rose/wiki/EDG-Installation-Instructions) and run `make show-edg-url`. However the url [https://edg-binaries.rosecompiler.org/roseBinaryEDG-5-0-aarch64-pc-linux-gnu-gnu-8-5.0.11.45.9.tar.gz ](https://edg-binaries.rosecompiler.org/roseBinaryEDG-5-0-aarch64-pc-linux-gnu-gnu-8-5.0.11.45.9.tar.gz ) is not available. Can EDG be installed for aarch64?

**Comment by tristanvdb** [comment]
We are not producing aarch64 binaries for EDG only x86. Sorry.
