### ISSUE TITLE
autoPar not getting Installed

### ISSUE THREAD

**Issue by ad1936** [rose-compiler/rose#234]
I tried to install complete rose-compiler in ubuntu 18.04, but all other tools are installed in the bin folder except autoPar. I have followed all the steps listed, I wish to know if any additional steps are required

**Comment by pinnown** [comment]
autoPar is a mothballed project that can be found in an older version of ROSE. It is not installed by default and you need to go to the project's directory to install it.

https://github.com/rose-compiler/rose/tree/v0.11.90.0/projects/autoParallelization
