### ISSUE TITLE
Parallelization of NPB benchmark using autoPar

### ISSUE THREAD

**Issue by Premas** [rose-compiler/rose#24]
Hi I am trying to parallelizing the "LU" benchmark of NPB suite, but I end up with the following error when parallelizing the file 'ssor.c'

/*Error while parallelizing ssor.c file */
autoPar[1873] 0.19439s rose[FATAL]: assertion failed:
autoPar[1873] 0.19447s rose[FATAL]:   /export/tmp.hudson-rose/jenkins/edg4x/workspace/development-edg-binary-RMC/COMPILER/gcc-4.4.7-default/EDGVERSION/4.9/src/frontend/CxxFrontend/EDG/edgRose/edgRose.C:5039
autoPar[1873] 0.19451s rose[FATAL]:   SgType* EDG_ROSE_Translation::convert_type(a_type*, bool)
autoPar[1873] 0.19454s rose[FATAL]:   required: vla_entry != __null
Aborted (core dumped)

[ssor.docx](https://github.com/rose-compiler/rose/files/1114848/ssor.docx)

**Comment by chunhualiao** [comment]
This should have been fixed.
