### ISSUE TITLE
Provide Rust source  compiler backend to unparser, to compile LLVM and Rose compiler to Rust source code

### ISSUE THREAD

**Issue by coderextreme** [rose-compiler/rose#242]
Translate C++ code to Rust.

Then everyone will be adopting Rust, perhaps!

This may be a duplicate.

**Comment by coderextreme** [comment]
It might be better to work with a LLVM codegen for producing Rust source code, since Rose compiler can target LLVM (which might be able to produce Rust code).

**Comment by pinnown** [comment]
Adding Rust support to Rose is a significant amount of effort and is currently not in out plan. We have discussed adding Rust and it may be added to the plan but that is not definitive.

Translating C++ to Rust would be a significant additional effort after Rust support is added.

**Comment by coderextreme** [comment]
I found
https://www.codeconvert.ai and C2Rust.  I may look at C2Rust in the the
future.
