### ISSUE TITLE
How do I change the front  from edg to clang?

### ISSUE THREAD

**Issue by XrazYang** [rose-compiler/rose#26]

**Comment by tristanvdb** [comment]
The experimental Clang frontend can be enable by configuring ROSE with --enable-clang-frontend. However, this requires Clang 3.8 compiled with REQUIRES_RTTI=1.

**Comment by milahu** [comment]
build fails when i remove EDG

undefined reference to ...

```
edg_main(int, char**, SgSourceFile&)
EDG_ROSE_Translation::clear_global_caches()
EDG_ROSE_Translation::edg_include_file_map[abi:cxx11]
EDG_ROSE_Translation::initDiagnostics()
EDG_ROSE_Translation::suppress_detection_of_transformations
vtable for FixupTypeReferencesOnMemoryPool
```

[rose-build-log-without-edg.txt](https://github.com/rose-compiler/rose/files/8769200/rose-build-log-without-edg.txt)

&rarr; must build with EDG and clang
