### ISSUE TITLE
Rose compiler tool - autoPar not converting c code correctly to openmp

### ISSUE THREAD

**Issue by KhatoonSaima** [rose-compiler/rose#27]
I installed rose compiler(version 0.9.10.54) on my linux centos7.5 and try to experiments on autoPar that has already given by Rose compiler. I have a normal c program given below and run the autoPar on this program using "autoPar test1.c"

    #include <stdio.h>

    int main(int argc, char *argv[]) {
    int N = 20;
    int total ;
    int i,j;

    for (j=0;j<N;j++) {
       for (i=0;i<N;i++) {
          total += i+j ;
       }
    }
    printf("%d\n", total) ;
    return 0;
    }

autoPar converts above "test1.c" prgram to the following openmp program "rose_test1.c" :-

    #include <stdio.h>
    #include <omp.h>

    int main(int argc,char *argv[])
    {
      int N = 20;
      int total;
      int i;
      int j;

    #pragma omp parallel for private (total,i,j) reduction (+:total)
    for (j = 0; j <= N - 1; j += 1) {

    #pragma omp parallel for private (total,i) reduction (+:total)
    for (i = 0; i <= N - 1; i += 1) {
      total += i + j;
     }
    }
    printf("%d\n",total);
    return 0;
    }

After that when I compile "rose_test1.c" openmp program using gcc(version 4.8.5) "gcc -fopenmp rose_test1.c "...get the following errors:

rose_test1.c: In function ‘main’:

rose_test1.c:13:34: error: ‘total’ appears more than once in data clauses

 #pragma omp parallel for private (total,i,j) reduction (+:total)
                                  ^
rose_test1.c:16:34: error: ‘total’ appears more than once in data clauses

 #pragma omp parallel for private (total,i) reduction (+:total)

I don't know why this type of translation problem happens...even i have older version of rose compiler which translate it correctly. Is this installation issue or gcc/openmp issue??

**Comment by chunhualiao** [comment]
@KhatoonSaima I think you should work within your home directory to avoid permission issues. I am closing this issue for now. Thanks!
