### ISSUE TITLE
autoPar code working

### ISSUE THREAD

**Issue by KhatoonSaima** [rose-compiler/rose#29]
Following are the codes of autoPar- A project build using rose compiler, Its difficult to understand what these lines are doing,Please help me to understand it?
 
        // X. Replace operators with their equivalent counterparts defined 
        // in "inline" annotations
          AstInterfaceImpl faImpl_1(body);
          CPPAstInterface fa_body(&faImpl_1);
          OperatorInlineRewrite()( fa_body, AstNodePtrImpl(body));

         // Pass annotations to arrayInterface and use them to collect 
         // alias info. function info etc.  
         ArrayAnnotation* annot = ArrayAnnotation::get_inst();
         ArrayInterface array_interface(*annot);
         array_interface.initialize(fa_body, AstNodePtrImpl(defn));
         array_interface.observe(fa_body);

        //FR(06/07/2011): aliasinfo was not set which caused segfault
        LoopTransformInterface::set_aliasInfo(&array_interface);

**Comment by chunhualiao** [comment]
@KhatoonSaima 
First paragraph of statements converts ROSE AST into another simplified AST and applies some transformation.  

The rest statements read semantics information about arrays and functions from an annotation (specification) files.  There is some documentation about what these annotations are: https://en.wikibooks.org/wiki/ROSE_Compiler_Framework/autoPar 

There are some IDEs ( netbeans and CLion) which can help you read source codes. You can quickly jump from a function call to its header file with some comments.
