### ISSUE TITLE
Get stuck in make BinarySerialIo.lo

### ISSUE THREAD

**Issue by FlyingOnion** [rose-compiler/rose#31]
Hello, I got stuck in `make` when it comes to BinarySerialIo.lo
This is the last few lines I got.
<pre>
make[5]: Entering directory '/home/ubuntu/rose/rose-build/src/midend'
make[5]: Nothing to be done for 'all-am'.
make[5]: Leaving directory '/home/ubuntu/rose/rose-build/src/midend'
make[4]: Leaving directory '/home/ubuntu/rose/rose-build/src/midend'
make[3]: Leaving directory '/home/ubuntu/rose/rose-build/src/midend'
Making all in backend
make[3]: Entering directory '/home/ubuntu/rose/rose-build/src/backend'
CXX      BinarySerialIo.lo
</pre>
It does not show any error messages. When I use `make -j4`, other tasks seems work normally
<pre>
make[3]: Entering directory '/home/ubuntu/rose/rose-build/src/backend'
  CXX      BinarySerialIo.lo
  CXX      AsmUnparser.lo
  CXX      AsmFunctionIndex.lo
  CXX      AsmUnparser_compat.lo
  CXX      unparseX86Asm.lo
  CXX      unparseArmAsm.lo
  CXX      unparsePowerpcAsm.lo
  CXX      unparseM68kAsm.lo
  CXX      unparseMipsAsm.lo
</pre>
There are still something wrong with this file. Someone could help?

**Comment by matzke1** [comment]
This is a large source file, in terms of header files, that requires substantial resources to compile. If your machine is under powered it might take a very long time.

**Comment by matzke1** [comment]
Our portability testing is not reporting any problems compiling this file, although it does take a while.
