### ISSUE TITLE
Rose compiler with spack

### ISSUE THREAD

**Issue by trecakov** [rose-compiler/rose#34]
Both master and 0.9.7.0 version are giving errors. 

==> Installing rose
==> Searching for binary cache of rose
==> Warning: No Spack mirrors are currently configured
==> No binary for rose found: installing from source
==> Cloning git repository: https://github.com/rose-compiler/rose.git on branch master
==> Already staged rose-master-4mg4kwou4mtdndu3docmiqprliuervbl in /software/packages/spack/var/spack/stage/rose-master-4mg4kwou4mtdndu3docmiqprliuervbl
1 out of 1 hunk FAILED -- saving rejects to file config/compiler-defs.m4.rej
==> Patch add_spack_compiler_recognition.patch failed.
==> Error: ProcessError: Command exited with status 1:
   '/usr/bin/patch' '-s' '-p' '1' '-i' '/software/packages/spack/var/spack/repos/builtin/packages/rose/add_spack_compiler_recognition.patch' '-d' '.' 

==> Installing rose
==> Searching for binary cache of rose
==> Warning: No Spack mirrors are currently configured
==> No binary for rose found: installing from source
==> Fetching https://github.com/rose-compiler/rose/archive/v0.9.7.0.tar.gz
######################################################################## 100.0%
==> Staging archive: /software/packages/spack/var/spack/stage/rose-0.9.7.0-xtr6vxbfwkjmdfm4vtvbnfnazmqkg62z/v0.9.7.0.tar.gz
==> Created stage in /software/packages/spack/var/spack/stage/rose-0.9.7.0-xtr6vxbfwkjmdfm4vtvbnfnazmqkg62z
1 out of 1 hunk FAILED -- saving rejects to file config/compiler-defs.m4.rej
==> Patch add_spack_compiler_recognition.patch failed.
==> Error: ProcessError: Command exited with status 1:
   '/usr/bin/patch' '-s' '-p' '1' '-i' '/software/packages/spack/var/spack/repos/builtin/packages/rose/add_spack_compiler_recognition.patch' '-d' '.'

**Comment by charlesareynolds** [comment]
https://github.com/rose-compiler/rose.git is now at version 0.9.10.242 - please try again.

**Comment by trecakov** [comment]
It did not work. However, I was able to install rose from https://github.com/rose-compiler/rose-develop.git.
