### ISSUE TITLE
OpenMP translator converts to a code that gives wrong result

### ISSUE THREAD

**Issue by AtanuBarai** [rose-compiler/rose#35]
I am trying to convert an OpenMP code using the translator. But it seems like the executable I produced after code conversion gives wrong result.

The code I am trying to convert using identityTranslator is

```
#include <omp.h>
#include <stdio.h>
static long num_steps = 10000;

int main()
{
    double x=0;
    double sum = 0.0, pi;
	unsigned i;
	double	step = 1.0/(double) num_steps;

    #pragma omp parallel for private(i,x) reduction(+:sum) schedule(static)
    for (i=0; i<num_steps; i=i+1)
	{
       	x=(i+0.5)*step;
       	sum = sum + 4.0/(1.0+x*x);
    }
      	
	pi=step*sum;
	printf("%f\n", pi);
}
```
The command I am using is 

> identityTranslator -rose:openmp:lowering  omp_pi.c

> ./a.out
I am getting the value 5.785765 but excepted output is 3.141593

**Comment by chunhualiao** [comment]
Hi, 
@AtanuBarai 
I just tried it myself. I got the expected result. Do you mind sharing the version of identityTranslator, the gomp omp runtime library you used, number of OpenMP threads used, and the generated rose_omp_pi.c file on your machine?  I put my info. below:

../rose-develop/configure --enable-edg_version=4.12 --prefix=/home/ubuntu/opt/rose_inst --with-boost=/home/ubuntu/opt/boost/1.61.0/gcc-4.9.3-default --with-CXX_DEBUG=-g --with-C_OPTIMIZE=-O0 --with-CXX_OPTIMIZE=-O0 --with-ROSE_LONG_MAKE_CHECK_RULE=yes --enable-languages=c++,fortran --enable-projects-directory --enable-tests-directory --with-gomp_omp_runtime_library=/usr/lib/gcc/x86_64-linux-gnu/4.9/

./identityTranslator --version
`
ROSE (version: 0.9.10.179)
  --- using ROSE SCM version:
      --- ID: 48552ccc7760d1addbd3c0af1fe39515a0c45d2d
      --- Timestamp: 2019-03-05 20:26:35 UTC
  --- using EDG C/C++ front-end version: edg-4.12
  --- using OFP Fortran parser version: ofp-0.8.3
  --- using Boost version: 1.61.0 (/home/ubuntu/opt/boost/1.61.0/gcc-4.9.3-default)
  --- using backend C compiler: gcc version: 4.9
  --- using backend C compiler path (as specified at configure time): gcc
  --- using backend C++ compiler: g++ version: 4.9
  --- using backend C++ compiler path (as specified at configure time): g++
  --- using original build tree path: /home/ubuntu/buildtree
  --- using instalation path: /home/ubuntu/opt/rose_inst
  --- using GNU readline version: unknown (readline is disabled)
  --- using libmagic version: unknown (libmagic is disabled)
  --- using yaml-cpp version: unknown (yaml-cpp is disabled)
  --- using lib-yices version: unknown (libyices is disabled)
`
 ./identityTranslator  -rose:openmp:lowering pi.c
$ ./a.out
3.141593
$ export OMP_NUM_THREADS=4
$ ./a.out
3.141593

 ./a.out
3.141593
$ cat rose_pi.c
`
#include <omp.h>
#include <stdio.h>
#include "libxomp.h"
static long num_steps = 10000;

struct OUT__1__3378___data
{
  void *sum_p;
  void *step_p;
}
;
static void OUT__1__3378__(void *__out_argv);

int main(argc,argv)
int argc;
char **argv;
{
  int status = 0;
  XOMP_init(argc,argv);
  double x = 0;
  double sum = 0.0;
  double pi;
  unsigned int i;
  double step = 1.0 / ((double )num_steps);
  struct OUT__1__3378___data __out_argv1__3378__;
  __out_argv1__3378__ . step_p = ((void *)(&step));
  __out_argv1__3378__ . sum_p = ((void *)(&sum));
  XOMP_parallel_start(OUT__1__3378__,&__out_argv1__3378__,1,0,"/home/ubuntu/opt/rose_inst/bin/pi.c",13);
  XOMP_parallel_end("/home/ubuntu/opt/rose_inst/bin/pi.c",18);
  pi = step * sum;
  printf("%f\n",pi);
  XOMP_terminate(status);
}

static void OUT__1__3378__(void *__out_argv)
{
  double *sum = (double *)(((struct OUT__1__3378___data *)__out_argv) -> sum_p);
  double *step = (double *)(((struct OUT__1__3378___data *)__out_argv) -> step_p);
  double _p_x;
  double _p_sum;
  _p_sum = 0;
  unsigned int _p_i;
  long p_index_;
  long p_lower_;
  long p_upper_;
  XOMP_loop_default((unsigned int )0,num_steps - 1,_p_i + ((unsigned int )1),&p_lower_,&p_upper_);
  for (p_index_ = p_lower_; ((long )p_index_) <= p_upper_; p_index_ = p_index_ + 1) {
    _p_x = (p_index_ + 0.5) *  *step;
    _p_sum = _p_sum + 4.0 / (1.0 + _p_x * _p_x);
  }
  XOMP_atomic_start();
   *sum =  *sum + _p_sum;
  XOMP_atomic_end();
  XOMP_barrier();
}
`

**Comment by AtanuBarai** [comment]
Hello @chunhualiao 

I have used the following command to build rose

$ ROSE_SRC/configure --prefix=$HOME/rose-installation-gomp --enable-languages=all --with-boost=$BOOST_ROOT --with-gomp_omp_runtime_library=/usr/lib/gcc/x86_64-linux-gnu/4.8.5

$ identityTranslator --version

> ROSE (version: 0.9.10.54)
>   --- using ROSE SCM version:
>       --- ID: e11cc2d5cb88bc196f5c80421699132c6843bda0
>       --- Timestamp: 2018-07-01 23:34:48 UTC
>   --- using EDG C/C++ front-end version: edg-4.9
>   --- using OFP Fortran parser version: ofp-0.8.3
>   --- using Boost version: 1.61.0 (/home/atanu/boost/1.61.0)
>   --- using backend C compiler: gcc version: 4.8
>   --- using backend C compiler path (as specified at configure time): gcc
>   --- using backend C++ compiler: g++ version: 4.8
>   --- using backend C++ compiler path (as specified at configure time): g++
>   --- using original build tree path: /home/atanu/LANL/rose_build
>   --- using instalation path: /home/atanu/rose-installation
>   --- using GNU readline version: unknown (readline is disabled)
>   --- using libmagic version: unknown (libmagic is disabled)
>   --- using yaml-cpp version: unknown (yaml-cpp is disabled)
>   --- using lib-yices version: unknown (libyices is disabled)

$ identityTranslator -rose:openmp:lowering  omp_pi.c
$ export OMP_NUM_THREADS=4
$ ./a.out
$ 5.303271
$ gcc --version
> gcc (Ubuntu 4.8.5-4ubuntu8) 4.8.5
> Copyright (C) 2015 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ cat rose_omp_pi.c

```
#include <omp.h>
#include <stdio.h>
#include "libxomp.h" 
static long num_steps = 10000;

struct OUT__1__4219___data 
{
  void *sum_p;
  void *step_p;
}
;
static void OUT__1__4219__(void *__out_argv);

int main(argc,argv)
int argc;
char **argv;
{
  int status = 0;
  XOMP_init(argc,argv);
  double x = 0;
  double sum = 0.0;
  double pi;
  unsigned int i;
  double step = 1.0 / ((double )num_steps);
  struct OUT__1__4219___data __out_argv1__4219__;
  __out_argv1__4219__ . step_p = ((void *)(&step));
  __out_argv1__4219__ . sum_p = ((void *)(&sum));
  XOMP_parallel_start(OUT__1__4219__,&__out_argv1__4219__,1,0,"/home/atanu/LANL/rose_compiler_test/omp_pi.c",12);
  XOMP_parallel_end("/home/atanu/LANL/rose_compiler_test/omp_pi.c",17);
  pi = step * sum;
  printf("%f\n",pi);
  XOMP_terminate(status);
}

static void OUT__1__4219__(void *__out_argv)
{
  double *sum = (double *)(((struct OUT__1__4219___data *)__out_argv) -> sum_p);
  double *step = (double *)(((struct OUT__1__4219___data *)__out_argv) -> step_p);
  double _p_x;
  double _p_sum;
  _p_sum = 0;
  unsigned int _p_i;
  long p_index_;
  long p_lower_;
  long p_upper_;
  XOMP_loop_default((unsigned int )0,num_steps - 1,_p_i + ((unsigned int )1),&p_lower_,&p_upper_);
  for (p_index_ = p_lower_; ((long )p_index_) <= p_upper_; p_index_ = p_index_ + 1) {
    _p_x = (p_index_ + 0.5) *  *step;
    _p_sum = _p_sum + 4.0 / (1.0 + _p_x * _p_x);
  }
  XOMP_atomic_start();
   *sum =  *sum + _p_sum;
  XOMP_atomic_end();
  XOMP_barrier();
}
```

**Comment by chunhualiao** [comment]
@AtanuBarai I diffed your rose_omp_pi.c with mine. They are identitical except for some temporary variable names. So I think the translation works properly. Are you using Ubuntu 18.04?  We are porting ROSE to it and already noticed some regression tests are failing. If so, I would suggest to use Ubuntu 16 for now while we sorting out some Ubuntu 18 issue.s

**Comment by AtanuBarai** [comment]
@chunhualiao Yes I am using Ubuntu 18.04. I will try using Ubuntu 16.04 as you suggested.
Thanks

**Comment by AtanuBarai** [comment]
@chunhualiao There is another issue that I noticed in the generated **rose_omp_pi.c** code. The call to XOMP_loop_default takes **_p_i + ((unsigned int )1)** as the stride. But _p_i is not initialized. On the other hand **_p_i + ((unsigned int )1)** is unsigned integer and **stride** is signed integer in **XOMP_loop_default** function. This is generating error **Error: in XOMP_loop_default() of xomp.c: stride must be positive for incremental iteration. stride = -358812** when I am trying to instrument the code.

Function call:
`XOMP_loop_default((unsigned int )0,num_steps - 1,_p_i + ((unsigned int )1),&p_lower_,&p_upper_);`

Implementation:
`extern void XOMP_loop_default(int lower, int upper, int stride, long* n_lower, long* n_upper)`

**Comment by chunhualiao** [comment]
@AtanuBarai I confirm the issues. I will have to find some quality time and fix them. In the meantime, you can manually fix it in the generated code and compile it ( identitityTranslaotor -v will expose all command lines you might need). Thanks!

**Comment by liaosvcaf** [comment]
Fixed by https://github.com/rose-compiler/rose/commit/41b6db98ca08001a7398ec1f38e08d479a945924

**Comment by chunhualiao** [comment]
https://github.com/rose-compiler/rose/commit/41b6db98ca08001a7398ec1f38e08d479a945924 fixes it.
