### ISSUE TITLE
Outdated installer script (Ubuntu 18.04)

### ISSUE THREAD

**Issue by mrigger** [rose-compiler/rose#36]
Hi, I tried to install ROSE on Ubuntu 18.04, using the `scripts/2017-03-ROSE-Unbuntu-16.04-VM-setup.sh` script, but the installation failed due to outdated dependencies. For example, the installer script attempts to install GCC 4.9, which is no longer available on this distribution. I could install the older version by adding another package source (using `apt-add-repository "deb http://us.archive.ubuntu.com/ubuntu/ xenial universe" && apt-add-repository "deb http://us.archive.ubuntu.com/ubuntu/ xenial main restricted"`), but then ran into the problem that the specified JDK is no longer available. Since the installation procedure is rather long, I expect also some other issues. Is there an up-to-date installation description?

**Comment by chunhualiao** [comment]
Try the following, let us know if you have any issues:
`
sudo apt-get update
sudo apt-get upgrade
  
sudo apt-get install git wget build-essential libtool flex bison python3-dev unzip perl-doc doxygen texlive libboost-all-dev gdb gcc g++ gfortran autoconf automake autotools libxml2-dev libdwarf-dev openjdk-8-jdk-headles openjdk-8-jre-headles graphviz

git clone https://github.com/rose-compiler/rose-develop
mkdir build-rose

cd rose-develop/

./build 

cd build-rose/

../rose-develop/configure --prefix=/home/demo/opt/rose-inst --enable-edg_version=4.12 --with-boost-libdir=/usr/lib/x86_64-linux-gnu --with-boost=/usr
 
make install-core -j4
`

**Comment by mrigger** [comment]
Thanks for your quick response!

When compiling with the commands above, I get the following error:
```
make[3]: Entering directory '/build-rose/src'
 /bin/mkdir -p '/home/demo/opt/rose-inst/lib'
 /bin/mkdir -p '/home/demo/opt/rose-inst/bin'
 /bin/bash ../libtool   --mode=install /usr/bin/install -c   librose.la '/home/demo/opt/rose-inst/lib'
 /usr/bin/install -c ../libtool '/home/demo/opt/rose-inst/bin'
 /bin/mkdir -p '/home/demo/opt/rose-inst/include/rose'
 /usr/bin/install -c -m 644 ../../rose-develop/src/rose.h ../../rose-develop/src/roseInternal.h ../../rose-develop/src/rose_msvc.h ../../rose-develop/src/msvc_stdint.h ../../rose-develop/src/roseSupport/utility_functionsImpl.C ../../rose-develop/src/midend/astProcessing/AstDOTGeneration.h ../../rose-develop/src/midend/astProcessing/AstDOTGenerationImpl.C ../../rose-develop/src/frontend/SageIII/sage3basic.h ../../rose-develop/src/frontend/SageIII/sage3basic.hhh ../../rose-develop/src/midend/astDiagnostics/AstConsistencyTests.h ../../rose-develop/src/backend/asmUnparser/AsmUnparser_compat.h '/home/demo/opt/rose-inst/include/rose'
 /bin/mkdir -p '/home/demo/opt/rose-inst/lib'
 /usr/bin/install -c -m 644 rose-config.cfg '/home/demo/opt/rose-inst/lib'
libtool: warning: relinking 'librose.la'
libtool: install: (cd /build-rose/src; /bin/bash "/build-rose/libtool"  --silent --tag CXX --mode=relink g++ -g -O2 -Wall -Wall -no-undefined -o librose.la -rpath /home/demo/opt/rose-inst/lib dummyCppFileForLibrose.lo -pthread -L/usr/lib/x86_64-linux-gnu ../src/3rdPartyLibraries/MSTL/libmstl.la ../src/3rdPartyLibraries/libharu-2.1.0/src/libhpdf.la ../src/backend/libbackend.la ../src/frontend/SageIII/libsage3.la frontend/CxxFrontend/EDG/libroseEDG.la frontend/OpenFortranParser_SAGE_Connection/libroseFortran.la ../src/frontend/BinaryFormats/libroseBinaryFormats.la ../src/frontend/BinaryLoader/libroseBinaryLoader.la ../src/midend/BinaryAnalysis/libbinaryMidend.la ../src/frontend/Disassemblers/libroseDisassemblers.la ../src/frontend/Partitioner2/libPartitioner.la frontend/X10_ROSE_Connection/libroseX10.la ../src/midend/programAnalysis/libprogramAnalysis.la ../src/midend/programTransformation/loopProcessing/libLoopProcessing.la ../src/midend/programTransformation/extractFunctionArgumentsNormalization/libExtractFunctionArgumentsNormalization.la ../src/midend/programTransformation/singleStatementToBlockNormalization/libSingleStatementToBlockNormalization.la ../src/midend/libmidend.la ../src/roseSupport/libroseSupport.la ../src/util/support/libsupport.la ../src/util/graphs/libgraphs.la ../src/util/libroseutil.la ../src/util/libroseSawyer.la ../src/roseExtensions/failSafe/libfailsafe.la -L/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server -ljvm -lm -ldl -L/usr/lib -lpython2.7 -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions -L/usr/lib -lz -lpthread -ldl -lutil -lboost_date_time -lboost_thread -lboost_filesystem -lboost_program_options -lboost_regex -lboost_system -lboost_serialization -lboost_wave -lboost_iostreams )
collect2: error: ld returned 1 exit status
libtool:   error: error: relink 'librose.la' with the above command before installing it
Makefile:1911: recipe for target 'install-libLTLIBRARIES' failed
make[3]: Leaving directory '/build-rose/src'
make[3]: *** [install-libLTLIBRARIES] Error 1
make[2]: *** [install-am] Error 2
Makefile:2311: recipe for target 'install-am' failed
make[2]: Leaving directory '/build-rose/src'
Makefile:2146: recipe for target 'install-recursive' failed
make[1]: Leaving directory '/build-rose/src'
make[1]: *** [install-recursive] Error 1
Makefile:2437: recipe for target 'install-core' failed
make: *** [install-core] Error 2
The command '/bin/sh -c cd build-rose/ && make install-core -j2' returned a non-zero code: 2
```

I created a `Dockerfile`, since it might help to reproduce the error. In addition to the packages above, I also had to install `ghostscript`:
```
FROM ubuntu:18.04
RUN apt-get update && apt-get install -y --no-install-recommends wget software-properties-common gpg-agent
RUN apt-get update && apt-get install -y git wget build-essential libtool flex bison python3-dev unzip perl-doc doxygen texlive libboost-all-dev gdb gcc g++ gfortran autoconf automake libxml2-dev libdwarf-dev graphviz openjdk-8-jdk-headless openjdk-8-jre-headless
RUN apt-get update && apt-get install -y ghostscript
RUN git clone https://github.com/rose-compiler/rose-develop
RUN mkdir build-rose && cd rose-develop/ && ./build
RUN cd build-rose/ && ../rose-develop/configure --prefix=/home/demo/opt/rose-inst --enable-edg_version=4.12 --with-boost-libdir=/usr/lib/x86_64-linux-gnu --with-boost=/usr --enable-languages=c,c++,fortran
RUN cd build-rose/ && make install-core -j2
```

**Comment by gleisonsdm** [comment]
Hi, I had some similar problems with ubuntu 18.04, so, I have few suggestions.

Try remove all versions of the boost you have installed on your computer, the installation process will install the correct one.
After that, please, try the commands as described in the link:
https://en.wikibooks.org/wiki/ROSE_Compiler_Framework/Installation#Instructions_for_Ubuntu_18.04

Seems to me you have some missing dependencies, as gcc-multilib and g++-multilib.

Let us know if you have any issues.

Regards

**Comment by mrigger** [comment]
Hi, thanks for your help! I tried following your instructions, but the error remains. Since I started from a fresh `Dockerfile`, boost was not installed. Even after I installed the dependencies as explained in the wikibooks article, the build failed with the same error.

**Comment by gleisonsdm** [comment]
Hi,

I created a Dockerfile, you can access it using the follow link:
[https://github.com/chunhualiao/rose-docker-image/tree/master/ubuntu18_Dockerfile](https://github.com/chunhualiao/rose-docker-image/tree/master/ubuntu18_Dockerfile)
Can you, please, use it? Then, and let me know if it works for you.

**Comment by chunhualiao** [comment]
For Ubuntu 18.04,  we now have updated instructions at : 
https://github.com/rose-compiler/rose/wiki/Step-by-step-installation-on-Ubuntu

Also https://github.com/rose-compiler/rose/wiki/Install-Using-apt-get
