### ISSUE TITLE
"VERSION" is missing during configuration

### ISSUE THREAD

**Issue by soaringzhang** [rose-compiler/rose#4]
I met a problem when running "configure": xxx/VERSION file does not exist.

Can anyone help to provide a hint on this?

Thanks!

**Comment by ian-bertolacci** [comment]
I filed the same issue:
https://github.com/rose-compiler/rose/issues/3

**Comment by prateek-khandelwal** [comment]
I am facing the same issue. Can anyone point me to a fix ?

**Comment by ian-bertolacci** [comment]
Try my patch which is listed at https://github.com/rose-compiler/rose/issues/3.

**Comment by prateek-khandelwal** [comment]
Hi @ian-bertolacci, the specific patch you mentioned didn't work, however, I initialized a git repo in the src root, and created a blank VERSION file, it seems to resolve this particular error.

I'll update if anything breaks again.

Cheers !

**Comment by jkipod** [comment]
Hi prateek-khandelwal, how exactly did you initialize git repo ?

**Comment by prateek-khandelwal** [comment]
Hi @jkipod,
Issue `git init` in the src root dir

**Comment by matzke1** [comment]
The VERSION file has been renamed to ROSE_VERSION. Also, when building ROSE from source, you must do so by cloning the Git repo. Downloading ROSE as a ZIP archive from GitHub doesn't work. We've asked GitHub for a way to remove that option, but they say it's a low priority.
