### ISSUE TITLE
Use clang-cl for targeting Windows builds

### ISSUE THREAD

**Issue by XVilka** [rose-compiler/rose#40]
I noticed you are working on the MSVC port, but the work has stalled.
And it is totally understandable why. Many projects experienced problems for supporting MSVC out of the box. Gladly there is a solution already - it is possible just to use [clang-cl](https://clang.llvm.org/docs/MSVCCompatibility.html) like [Google did for Chrome](http://blog.llvm.org/2018/03/clang-is-now-used-to-build-chrome-for.html) or [Mozilla for Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1443590). And it is [easily integrated with CMake](https://github.com/ProdriveTechnologies/clang-msvc-sdk).

**Comment by tristanvdb** [comment]
The goal of this effort is to support Windows through MSVC instead of simply supporting Windows.
