### ISSUE TITLE
Rose compiler is not generating the identityTranslator

### ISSUE THREAD

**Issue by AtanuBarai** [rose-compiler/rose#42]
I am trying to install rose compiler on CentOS 7. Configure, build and installation terminates normally. But still I can't see the **identityTranslator** in the bin directory. I am using openjdk 8. Rose version 0.9.11.0.

**Comment by tristanvdb** [comment]
Hi, 
We recently change some of the target for our top makefile and the default binary name. The targets are:
 - **core**: compile ROSE's core
 - **check-core**: run hello-world through the ROSE's core
 - **install-core**: install ROSE's core

**Comment by AtanuBarai** [comment]
Hi,

Basically, I was using *identityTranslator* from version 0.9.10.0 of rose.
It worked fine when I used *make install-core *to build rose compiler as it
generated the *identityTranslator. *But in version  0.9.11.0 its not
working.

**Comment by tristanvdb** [comment]
You can either run **make install-tools** or use the binary **rose-compiler**.

Thanks,
-Tristan
