### ISSUE TITLE
EDG download error during "make rose-core"

### ISSUE THREAD

**Issue by soaringzhang** [rose-compiler/rose#43]
I got this error while building the latest version (in release branch) so far:

Downloading EDG binary tarball: roseBinaryEDG-5-0-x86_64-pc-linux-gnu-gnu-4.8-4.7690a49e061479d60c51a700bdb0ab34076829e2.tar.gz
error: the EDG binary tarball is not available (or the web site is not reachable).
Please contact rose-public@nersc.gov to troubleshoot this error.
make[4]: *** [EDG.tar.gz] Error 1

By printing the wget command, I got the full URL as http://www.rosecompiler.org/edg_binaries/, where there are quite a lot of .tar.gz files with different signatures. But it seems the directory has not been updated since dec 2018. And there is not the file with the signature required by the latest release source code.

So are there any new EDG tarballs to be updated into the edg_binaries/ directory? Or any way to workaround this build issue?

**Comment by tristanvdb** [comment]
Morning,

It seems that you are having two issues:
 (1) GCC 4.8 is not supported by ROSE anymore (we no longer distribute the EDG binaries for it).
 (2) The URL seems wrong (outdated), are you sure that it is the latest release? The current release is v0.9.11.0. You can verify your version with the ROSE_VERSION file at the top of the repository or look at the last commit in git's log.

Thanks,
-Tristan

**Comment by yogitanegi** [comment]
Hi,

I am facing the same issue while installing ROSE version 0.9.10.54 

The error is -

Downloading EDG binary tarball: roseBinaryEDG-4-9-x86_64-pc-linux-gnu-gnu-4.8-4.82daf656b47602afa41dc38d5a30fa107fbc1e7b.tar.gz
error: the EDG binary tarball is not available (or the web site is not reachable).
Please contact rose-public@nersc.gov to troubleshoot this error.
make[4]: *** [EDG.tar.gz] Error 1

The gcc version in my machine is 4.8.5.
As GCC 4.8 is not supported by ROSE anymore, can anyone please tell me for which version of GCC, the EDG tarball is now being distributed?
Also, will ROSE version 0.9.10.54 support that EDG tarball?
If not, please guide me regarding download steps for latest ROSE compiler.

Thanks,
Yogita
