### ISSUE TITLE
[Outliner] Scope Reuse

### ISSUE THREAD

**Issue by forflo** [rose-compiler/rose#45]
Hi!

## Status Quo

When using the AST-Outliner defined in `src/midend/programTransformation/astOutlining/Outlining.hh` I noticed some strange behaviour:

Given this snippet:
```c
#pragma OUTL
statement();
```

The outliner correctly generates `void __OUT__BLA() { statement(); }`. However, the outliner outlines the basic block

```c
#pragma OUTL
{
  statement1();
  statement2();
}
```

into the following function:

```c
void __OUT__BLA2()
{
  statement1();
  statement2();
}
```

Whereas it really should be

```c
void __OUT__BLA2()
{
  {
  statement1();
  statement2();
  }
}
```

# Reasons for the change

1. Consistency of Semantics

Currently, Outlining _only one_ statement adds one scope (the function scope) encapsulating the subject. In contrast, outlining a scope does not preserve the scope. After the transformation this scope will be recycled to serve as the scope of the function definition.

In other words: 

Outlining(S) => void OUT(...) { S }, iff S notAstType(SgBasicBlock)
Outlining(S) => void OUT(...) { getNthStmt(S, 0); getNthStmt(S, 1); ... }, iff S hasType(SgBasicBlock)

2. Practical usage

In my current project, I need to process OpenMP 5 (which Rose does not currently accept fully using `-rose:OpenMP:ast_only`). Also, I need to detect special combinations of target offloading constructs. For example, consider the following (contrived) code:

```c
#pragma omp target data map(p[0:N], v1, v2)
#pragma omp fnord1 santa(fi, fu)
#pragma omp fnord2 clause(fi, fu)
#pragma omp fnord3 santa(fi, fu) clause(bar, foo)
#pragma omp parallel
{
  for (int i = 0; i < N; i++) {
      p[i] = v1[i] * v2[i];
  }

  for (int i = 4; i < N; i++) {
      p[i] = v1[i] * v2[i];
  }
}
```

In the first step, this should be transformed into:

```c
static void OUT__1__4419__(int N,float **pp__,float *v1,float *v2)
{
#pragma omp fnord1 santa(fi, fu)
#pragma omp fnord2 clause(fi, fu)
#pragma omp fnord3 santa(fi, fu) clause(bar, foo)
#pragma omp parallel 
  {
  for (int i = 0; i < N; i++) {
      p[i] = v1[i] * v2[i];
  }

  for (int i = 4; i < N; i++) {
      p[i] = v1[i] * v2[i];
  }
  }
}
```

However, because of Rose's scope reuse, what actually gets generated is:

```c
static void OUT__1__4419__(int N,float **pp__,float *v1,float *v2)
{
#pragma omp fnord1 santa(fi, fu)
#pragma omp fnord2 clause(fi, fu)
#pragma omp fnord3 santa(fi, fu) clause(bar, foo)
#pragma omp parallel 
  for (int i = 0; i < N; i++) {
      p[i] = v1[i] * v2[i];
  }

  for (int i = 4; i < N; i++) {
      p[i] = v1[i] * v2[i];
  }
}
```

Which completely changes the semantics of the openmp pragmas since those only address the directly succeeding complete statement (the first for loop).

I know that a workaround would have been possible by wrapping the scope into another scope before outlining, but pathing ROSE posed to be much nicer here :)

3. *Patch exists* 

I already patched my local installation of the Outliner by introducing a boolean variable `naturalScopeHandling` in namespace Outliner, by default set to `false`. I made sure that the default semantics of Rose's outliner does not change.

Are you interested in accepting a PR?

**Comment by chunhualiao** [comment]
Hi,

Thanks for your insights for the outliner and OpenMP lowering.

 I think the problem you have is mostly caused by some missing feature in
your OpenMP AST design.

For the OpenMP target example, a proper designed AST should have a target
node representing the region to be offloaded to GPU.  The target node
should have a scoped block containing verything. The outliner then can
properly outline the entire code region, without breaking the region into
two parts and generating wrong code like you just described.


I actually developed openmp accelerator support several years ago using the
outliner . I don't remember I encountereed your issues for similar input
code. Please check it out at :

https://en.m.wikibooks.org/wiki/ROSE_Compiler_Framework/OpenMP_Acclerator_Model_Implementation

Thanks.

**Comment by forflo** [comment]
> Thanks for your insights for the outliner and OpenMP lowering.

Sure!

>  I think the problem you have is mostly caused by some missing feature in
your OpenMP AST design.
> For the OpenMP target example, a proper designed AST should have a target
node representing the region to be offloaded to GPU.  The target node
should have a scoped block containing verything. [...]

I disagree. The outliner must work consistently without having to replace the OpenMP pragmas to AST-Noses. My example shows the opposite. Also cf. `1. Consistency of Semantics` from above: 

```
Outlining(S) => void OUT(...) { S }, iff S notAstType(SgBasicBlock)
Outlining(S) => void OUT(...) { getNthStmt(S, 0); getNthStmt(S, 1); ... }, iff S hasType(SgBasicBlock)
```

Where `Outlining(S) => void OUT(...) { S }` would eliminate a special case in many tool implementations and thus make the outliner more usable by providing more composability.

> I actually developed openmp accelerator support several years ago using the
outliner . I don't remember I encountereed your issues for similar input
code. Please check it out at :

Yes, I am aware of that. I am quite fond of your OpenMP 4.0 target support (which you achieved by way of lifting pragmas to SgOmp-AST-Nodes. However, I am not currently able to use this feature since it seems to fail for non-4.0 openmp pragmas instead of leaving them unchanged (cf. code below).

```c
#include <vector>

int main(void) {
        std::vector<int> v1{1,2,3};
        int res = 0;
        #pragma omp target map(v1, res)
        #pragma omp nonOmp4
        #pragma omp parallel for
                for (int i = 0; i < 3; ++i) {
                        res += v1[i];
                }

        return res;
}
```

sadly produces:

```shell
forflo@ubuntu-bionic:~$ rose-c++ -rose:OpenMP:ast_only foo.cpp
Error when parsing pragma:
	 omp nonOmp4
	 associated with node at line 8
 syntax error, unexpected ID_EXPRESSION!
rose-c++: ../../../../rose/src/frontend/SageIII/ompparser.yy:1384: int omp_error(const char*): Assertion `0' failed.
Aborted (core dumped)
forflo@ubuntu-bionic:~$ rose-c++ --version
ROSE (version: 0.9.11.0)
  --- using ROSE SCM version:
      --- ID: 93075545a3810529149fcca189e0181f31017e93
      --- Timestamp: 2019-05-07 23:22:40 UTC
```

**Comment by chunhualiao** [comment]
A consistent algorithm of outlining in my view (actually the current
algorithm)

To Outline S: S could be either a single statement or a block of statements.

If S  is a single statement. Then Normalize S to make it a statement
inside a basic block.

Then consistently apply the following transformation:

Outlining(S) => void OUT(...) { getNthStmt(S, 0); getNthStmt(S, 1); ... },

iff S hasType(SgBasicBlock)

For this algorithm, there is no extra scope introduced in the generated code.

An algorithm introducing extra scope would be:

Outlining(S) => void OUT(...)

 {

{ getNthStmt(S, 0);

getNthStmt(S, 1); ...

}

},
iff S hasType(SgBasicBlock）

The bottomline, I think the current outlining works fine.
Normalization is a best practice to enable transform variants of AST
in a uniformed way and reuse the actual transformation code.
Transforming things differently is the real inconsistency in your
design.
