### ISSUE TITLE
[Installation] Linker issues with libroseEDG.a

### ISSUE THREAD

**Issue by forflo** [rose-compiler/rose#47]
Hello Everyone,

I am currently compiling ROSE for my Archlinux system. My run of `make install-core` terminates with an error though. 

## The Context

- g++-7.4.1 
- boost-1.69. 

Call to configure:

```shell
CXX='g++-7' CC='gcc-7' \
  CXXFLAGS='-Wall -Wno-unused-local-typedefs -Wno-attributes' ../ROSE/configure \
        --enable-assertion-behavior=abort \
        --prefix=/home/<user>/opt/rose_inst \
        --with-CFLAGS=-fPIC \
        --with-C_WARNINGS='-Wall -Wno-unused-local-typedefs -Wno-attributes' \
        --with-CXX_WARNINGS='-Wall -Wno-unused-local-typedefs -Wno-attributes' \
        --with-boost=/usr \
        --with-boost-libdir=/usr/lib/ \
        --enable-languages=c,c++ \
        --without-sqlite3 --without-libreadline --without-magic \
        --without-wt --without-yices --without-pch \
        --without-haskell
```

## The Symtoms

```
  CXXLD    librose.la
  <output shortened for brevity>
  CXXLD    rose-c++
  CXXLD    rose-cc
/usr/bin/ld: /home/<user>/BUILD-ROSE/BUILD/src/.libs/librose.so: undefined reference to `boost::system::system_category()'
/usr/bin/ld: /home/<user>/BUILD-ROSE/BUILD/src/.libs/librose.so: undefined reference to `boost::system::generic_category()'
```

The commands
```shell
cd BUILD-ROSE/BUILD/
find . -name "*.a" | parallel --tag "readelf -Wr {} | grep 'system_category'"
cd src/frontend/CxxFrontend/
mkdir __examine && cp EDG.tar.gz __examine 
cd __examine
tar -xvf EDG.tar.gz
cd roseBinaryEDG.../.libs
readelf -Wr libroseEDG.a | grep '_ZN5boost6system15system_categoryEv'
```

show that libroseEDG.a contains references to boost::system::system_category (as well as generic_category). Beginning with boost 1.69, these are **not resolvable** anymore. 

Using readelf -Wr librose.so shows that these unresolvable references then propagate into the final library:

```
./.libs/librose.so	00000000037a4670  0000007000000007 R_X86_64_JUMP_SLOT     0000000000000000 _ZN5boost6system15system_categoryEv + 0
```

In 1.69 boost::system is a header-only library. They do provide a library stub libboost_system.so **which does not export** {generic,system}_category anymore though. There is no easy way to enable this on modern systems.

## The Bug

Either the `build` or the `configure` script failed to generate the right URL for `EDG.tar.gz` or I did not correctly configure ROSE. What am I doing wrong?

## Possible Solutions

`configure` seems to allow linking against a specific instance of `libboost_system`. However, I would really refrain going this path because I has several drawbacks:

- I don't know the _exact_ version of boost that libroseEDG.a was built against
- Linking against a specific version of libboost_system might work now but a system update to boost-1.70 could break things in the future

## Proper Solutions

- Include `libboost_system.so` in your `EDG.tar.gz`
- Fix `.configure` to automatically download a binary built with boost-1.69

Could you please help me solve this?

Thank you &
Best regards

**Comment by pinnown** [comment]
There is currently an issue with the binary when using boost 1.69 and later. While we fix this switching to Boost 1.67 should fix this issue.

**Comment by tristanvdb** [comment]
This is a known issue due to boost::filesystem being instantiated from the EDG connection. We are investigating solutions. At this time, using Boost 1.67 is the best course of action.
Thanks,

**Comment by skyneu** [comment]
Is this still true? (i.e. Is it still necessary to use Boost 1.67?)
