### ISSUE TITLE
Missing Check in SageInterface::getProject(const SgNone *node)

### ISSUE THREAD

**Issue by forflo** [rose-compiler/rose#49]
Hello Everyone,

in `src/frontend/SageIII/sageInterface/sageInterface.C` in [line 4711](https://github.com/rose-compiler/rose/blob/93075545a3810529149fcca189e0181f31017e93/src/frontend/SageIII/sageInterface/sageInterface.C#L4711) the function `getProject(const SgNode *node)` does return NULL when given an SgProject. Clearly getProject(foo) must return true if isSgProject(foo) is not null, that is if project happens to be a project.

Instead the function returns `nullptr`!

Best regards

**Comment by matzke1** [comment]
JIRA issue ROSE-2151 internally. Thanks for the report.

**Comment by pinnown** [comment]
Fixed in develop branch.
