### ISSUE TITLE
SageBuilder::buildNondefiningFunctionDeclaration does not check ScopeStack to be non-empty

### ISSUE THREAD

**Issue by forflo** [rose-compiler/rose#50]
Hello Everyone,

a particular [function overload](https://github.com/rose-compiler/rose/blob/93075545a3810529149fcca189e0181f31017e93/tests/nonsmoke/functional/roseTests/astInterfaceTests/buildFunctionDeclaration.C#L32) SageBuilder::buildNondefiningFunctionDeclaration -- as demonstrated in `tests/nonsmoke/functional/roseTests/astInterfaceTests/buildFunctionDeclaration.C` does not check whether the ScopeStack is non-empty.

This can be seen if you remove [this line](https://github.com/rose-compiler/rose/blob/93075545a3810529149fcca189e0181f31017e93/tests/nonsmoke/functional/roseTests/astInterfaceTests/buildFunctionDeclaration.C#L17).

Expected behaviour: Error message about ScopeStack being non-empty.

Actual behaviour: Segmentation fault

Best regards

**Comment by chunhualiao** [comment]
Addressed it by https://github.com/rose-compiler/rose/commit/d2262f856365311c1d20395cf8ca2ab06794a171
