### ISSUE TITLE
[Compat] Missing declaration to GCC's `__builtin_swap16` in `rose_edg_required_macros_and_functions.h`

### ISSUE THREAD

**Issue by forflo** [rose-compiler/rose#51]
Hello everyone,

I just noticed that `rose_edg_required_macros_and_functions.h` is missing the declaration for GCC builtin `__builtin_swap16`.

- In glibc-2.27: the buildin does not exist. Here it is defined as macro.
- In glibc-2.29-4, which I have installed, it *does* exist!

I tried compiling with `-nosysinc` and giving rose include paths to `glibc-2.27` withouth success.

# Code causing the error:

```c++
#include <algorithm>
#include <random>
#include <cstring>

int main(void) { return 0; }
```

# Quickfix:

I added this code from `byteswap-16.h` in glibc-2.27 to the file `rose_edg_required_macros_and_functions.h`

```c
#ifdef __GNUC__
# if __GNUC__ >= 2
#  define __bswap_16(x) \
     (__extension__							      \
      ({ unsigned short int __v, __x = (unsigned short int) (x);	      \
	 if (__builtin_constant_p (__x))				      \
	   __v = __bswap_constant_16 (__x);				      \
	 else								      \
	   __asm__ ("rorw $8, %w0"					      \
		    : "=r" (__v)					      \
		    : "0" (__x)						      \
		    : "cc");						      \
	 __v; }))
# else
/* This is better than nothing.  */
#  define __bswap_16(x) \
     (__extension__							      \
      ({ unsigned short int __x = (unsigned short int) (x);		      \
	 __bswap_constant_16 (__x); }))
# endif
#else
static __inline unsigned short int
__bswap_16 (unsigned short int __bsx)
{
  return __bswap_constant_16 (__bsx);
}
#endif
```

This fixes parsing. However I don't know exactly how you handle this kind of compat. issue. Probably a fwd. declaration would have been sufficient also. Is there any further documentation on the subject?

Thanks &
Best regards

**Comment by tristanvdb** [comment]
You are right that a forward declaration is sufficient. Actually, we usually prefer forward declarations and always avoid macros. Macros change the code before it is parsed changing the AST. Definitions simply increase the code size for no reason (while also setting a behavior that might be different from the backend compiler).
There is one more consideration: constexpr builtins... these might be used when template are instantiated so they need a definition. In that case, we encapsulate the behavior in another function called __builtin_rose_*. I am fixing one of these (__builtin_clz used by std::ratio) and I will add __bswap_16 in the same merge.

**Comment by tristanvdb** [comment]
__builtin_swap16 is available in the develop branch.
