### ISSUE TITLE
Suggestion for code style

### ISSUE THREAD

**Issue by forflo** [rose-compiler/rose#56]
Hello everyone,

I happened to notice, that there are a lot of comments of the style `<author> (<data>): <something>`.

During my time reading parts of the ROSE source code, I also noticed, that <something> often contains information that is obvious or redundant. Redundant comment information make the code increasingly hard to read. Also, some of the comments seem to be severely out-of-date (or not in-sync with the code anymore). This makes understanding source code even harder.

Maybe you would want to incrementally change your commenting habits in order to only provide useful information?

However, if you are required to do this kind of commenting by LLNL policy, just ingore this succestion :wink:.

Thanks & Best regards

**Comment by tristanvdb** [comment]
Hello,
We are transitioning to take advantage of our issue tracker (leading to less redundant information), However, it takes time to adopt.
Thanks,
