### ISSUE TITLE
Build failures on CentOS 7.6.1810 due to undefined references 

### ISSUE THREAD

**Issue by AjitDingankar** [rose-compiler/rose#58]
ROSE installation from instructions at
https://github.com/rose-compiler/rose/wiki/Step-by-step-installation-on-CentOS 
fails on 
make core -j10 
with errors of undefined reference to Sg synbols: 
  CXXLD    rose-config
  CXXLD    rose-compiler
  CXXLD    rose-cc
  CXXLD    rose-c++
/home/ajit/rose/build/src/.libs/librose.so: undefined reference to `SgInitializedName::set_microsoft_uuid_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'

I downloaded EDG binaries according to instructions for "no network connection" on:
https://github.com/rose-compiler/rose/wiki/EDG-Installation-Instructions 
Still get similar errors, ending in: 

/home/ajit/rose/build/src/.libs/librose.so: undefined reference to `Rose::StringUtility::numberToString[abi:cxx11](int)'
/home/ajit/rose/build/src/.libs/librose.so: undefined reference to `EDG_ROSE_Translation::edg_include_file_map'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:2030: rose-c++] Error 1
make[2]: Leaving directory '/home/ajit/rose/build/src'
make[1]: *** [Makefile:2204: all-recursive] Error 1
make[1]: Leaving directory '/home/ajit/rose/build/src'
make: *** [Makefile:2378: core] Error 2

I'd appreciate any help! 

Thanks, 
Ajit
====

**Comment by pinnown** [comment]
Thanks for the heads up. We are aware of this issue and are working to resolve it.
