### ISSUE TITLE
Include Sage IR lowering library

### ISSUE THREAD

**Issue by forflo** [rose-compiler/rose#59]
Hi everyone,

as discussed with @chunhualiao  during IWOMP'19, me and my colleagues would very much appreciate if you could include your Sage IR lowering libraries (which are currently only developed and used internally).

AST lowering would enable us to develop an AST analysis which will only be reasonable to implement for simplified Sage IR. We plan to file a PR of this analysis in the future as well.

Is it possible for you to include this feature?

Best regards
Florian

**Comment by chunhualiao** [comment]
This is a task to Markus since the AST normalization in question is his work.  The users is interested in using his work.

**Comment by forflo** [comment]
Hey Leo,

thank you very much for forwarding the message. @mschordan maybe we can collaborate together to integrate your features into ROSE?

Best regards
Florian

**Comment by mschordan** [comment]
Hi Florian,
I have integrated the normalization into a library in one of the projects such that if you install that library you can start using it already now (send me an e-mail for futher instructions), or you wait until it is integrated into rose-core.

**Comment by mschordan** [comment]
The Normalization is now available in ROSE by installing one of the projects' additional libraries:
cd <build-tree>/projects/CodeThorn/src
run make && make install
headers are installed in <rose-install-path>/includes/rose/codethorn
add to your code: #include "rose/codethorn/Normalization.h" 
and link with the additional library: -lcodethorn
You can invoke the normalization/lowering with: 
Normalization norm; norm.run(astnode,2); // astnode usually is a pointer to a SgProject node.
Any normalized code can be unparsed and compiled. It's well tested for C.
