### ISSUE TITLE
EDG binary tarball not available

### ISSUE THREAD

**Issue by yogitanegi** [rose-compiler/rose#60]
Hi,

I am getting EDG tarball download error while installing ROSE version 0.9.10.54

The error is -

Downloading EDG binary tarball: roseBinaryEDG-4-9-x86_64-pc-linux-gnu-gnu-4.8-4.82daf656b47602afa41dc38d5a30fa107fbc1e7b.tar.gz
error: the EDG binary tarball is not available (or the web site is not reachable).
Please contact rose-public@nersc.gov to troubleshoot this error.
make[4]: *** [EDG.tar.gz] Error 1

The gcc version in my machine is 4.8.5.
As GCC 4.8 is not supported by ROSE anymore, can anyone please tell me for which version of GCC, the EDG tarball is now being distributed?
Also, will ROSE version 0.9.10.54 support that EDG tarball?
If not, please guide me regarding download steps for latest ROSE compiler.

Thanks,
Yogita

**Comment by pinnown** [comment]
The server issue has been resolved and you should now be able to download this tarball. Each version of ROSE has a set of EDG tarballs attached to it so older versions of ROSE still use the same tarballs as when the version released.

If you would like to install a newer version of ROSE the instructions can be found at https://github.com/rose-compiler/rose/wiki/How-to-Set-Up-ROSE. 

Information about the version we are currently supporting can be found at https://github.com/rose-compiler/rose/wiki/Supported-Configurations

**Comment by yogitanegi** [comment]
Its getting downloaded now.Thanks @pinnown for your comment

**Comment by yogitanegi** [comment]
Hi @pinnown,

I am facing the same issue (EDG binary tarball not available) since yesterday.
Can you help me on this?

Thanks,
Yogita

**Comment by yogitanegi** [comment]
> The server issue has been resolved and you should now be able to download this tarball. Each version of ROSE has a set of EDG tarballs attached to it so older versions of ROSE still use the same tarballs as when the version released.
> 
> If you would like to install a newer version of ROSE the instructions can be found at https://github.com/rose-compiler/rose/wiki/How-to-Set-Up-ROSE.
> 
> Information about the version we are currently supporting can be found at https://github.com/rose-compiler/rose/wiki/Supported-Configurations

I am facing the same issue, EDG tarball download error again(since yesterday). Can you guide me how to resolve it?
Thanks,
Yogita
