### ISSUE TITLE
crash when copying a function with a forward function declaration in the function body

### ISSUE THREAD

**Issue by seanchen1002** [rose-compiler/rose#63]
When I try to copy a function with a forward function declaration in the function body, ROSE crashed.

the example input is as following:
```
void test_func() {
  int a;
  void sub(int);
  sub(a);
}
```
my code is similar like as following:
```
#include<rose.h>
using namespace Rose;                                
int
main (int argc, char* argv[])
{
  // Initialize and check compatibility. See Rose::initialize
  ROSE_INITIALIZE;
  std::vector<std::string> args;
  for (int i = 0; i < argc; ++i)
    args.push_back(std::string(argv[i]));
  SgProject *proj = frontend(args);
  std::string sFileName = "copy_out.cpp";
  SgSourceFile *new_file = isSgSourceFile(SageBuilder::buildFile(
      sFileName, sFileName, proj));
  Rose_STL_Container\<SgNode *\> vec_funcs =
      NodeQuery::querySubTree(proj, V_SgFunctionDeclaration);
  for (auto func : vec_funcs) {
    auto func_decl = isSgFunctionDeclaration(func);
    if (func_decl && func_decl->get_name() == "test_func") {
      SgStatement *sg_new_func = SageInterface::copyStatement(
          func_decl);
      new_file->get_globalScope()->append_declaration(isSgFunctionDeclaration(sg_new_func));
    }
  }

  return backend(proj);
}
```

**Comment by seanchen1002** [comment]
The crash message is as following:
Error: declarationAssociatedWithSymbol->get_symbol_from_symbol_table() == NULL
     declarationAssociatedWithSymbol = 0x7fa1421e06e0 = SgFunctionDeclaration = test_func
Inside of Sg_File_Info::display(this) of this pointer = 0x7fa14149f000
     isTransformation                      = true (part of a transformation)
     isCompilerGenerated                   = false
     isOutputInCodeGeneration              = true (output in code generator)
     isShared                              = false
     isFrontendSpecific                    = false
     isSourcePositionUnavailableInFrontend = false
     isCommentOrDirective                  = false
     isToken                               = false
     isDefaultArgument                     = false
     isImplicitCast                        = false
filename and line, column info should be invalid for transformation or compiler generated objects
we print their values anyway for your reference
     filename = transformation
     line     = 0  column = 0
     physical_file_id       = -3 = transformation
     physical_line          = 0
     source_sequence_number = 0
Inside of Sg_File_Info::display(declarationAssociatedWithSymbol) of this pointer = 0x7fa14149f000
     isTransformation                      = true (part of a transformation)
     isCompilerGenerated                   = false
     isOutputInCodeGeneration              = true (output in code generator)
     isShared                              = false
     isFrontendSpecific                    = false
     isSourcePositionUnavailableInFrontend = false
     isCommentOrDirective                  = false
     isToken                               = false
     isDefaultArgument                     = false
     isImplicitCast                        = false
filename and line, column info should be invalid for transformation or compiler generated objects
we print their values anyway for your reference
     filename = transformation
     line     = 0  column = 0
     physical_file_id       = -3 = transformation
     physical_line          = 0
     source_sequence_number = 0
In get_declaration_associated_with_symbol(): declarationAssociatedWithSymbol = 0x7fa1421e06e0 = SgFunctionDeclaration = t
est_func
In get_declaration_associated_with_symbol(): declarationAssociatedWithSymbol scope = 0x7fa14275b120 = SgGlobal = 0x7fa142
75b120
rose_exe: Cxx_Grammar.C:150863: SgDeclarationStatement* SgDeclarationStatement::get_declaration_associated_with_symbol()
const: Assertion `declarationAssociatedWithSymbol->get_symbol_from_symbol_table() != __null' failed.
Aborted

**Comment by chunhualiao** [comment]
The deep copy interface is tested for copying things to the same file, not across files. 

https://github.com/rose-compiler/rose/blob/release/tests/nonsmoke/functional/roseTests/astInterfaceTests/deepCopy.C

Additional testing is needed.
