### ISSUE TITLE
Copying typedef with struct definition will lose struct definition

### ISSUE THREAD

**Issue by seanchen1002** [rose-compiler/rose#64]
Hi,
when I try to copy a typedef declaration with struct definition, the output will lose struct definition
my input code is as following 
```
typedef struct st {
  int a;
} st;
st a;
typedef struct {
  int a;
} st2;
st2 b;
typedef int INT;
```
my code is as following:
```
#include<rose.h>
using namespace Rose;                                   // the ROSE team is migrating everything to this namespace
int
main (int argc, char* argv[])
{
  // Initialize and check compatibility. See Rose::initialize
  ROSE_INITIALIZE;
  std::vector<std::string> args;
  for (int i = 0; i < argc; ++i)
    args.push_back(std::string(argv[i]));
  SgProject *proj = frontend(args);
  std::string sFileName = "copy_out.cpp";
  SgSourceFile *new_file = isSgSourceFile(SageBuilder::buildFile(
      sFileName, sFileName, proj));
  Rose_STL_Container<SgNode *> vec_tydefs =
      NodeQuery::querySubTree(proj, V_SgTypedefDeclaration);
  for (auto decl : vec_tydefs) {
    auto typedef_decl = isSgTypedefDeclaration(decl);
    SgStatement *sg_new_decl = SageInterface::copyStatement(
        typedef_decl);
    new_file->get_globalScope()->append_declaration(isSgTypedefDeclaration(sg_new_decl));
  }

  return backend(proj);
}
```

**Comment by seanchen1002** [comment]
But the output in file copy_out.cpp is as following:
`typedef struct st {}st;
typedef struct {}st2;
typedef int INT;`

**Comment by tristanvdb** [comment]
I obtain the following output which is wrong but slightly different:
```
typedef struct st {
int a;}st;
typedef struct {}st2;
typedef int INT;
```
Are you sure it was missing in both struct definition before? It points to an issue for anonymous structs and I'd like to know if the other case was fixed recently...

FYI: I do use `-DSKIP_ROSE_BUILTIN_DECLARATIONS` when running the tool which prevent ROSE's builtins from being include in the translation units. That is a useful option for debugging with minimized reproducers.
