### ISSUE TITLE
Where will floating expression happen in ROSE framework?

### ISSUE THREAD

**Issue by seanchen1002** [rose-compiler/rose#66]
Hi, everyone, 
floating expresion means ROSE SgExpression which is not in ROSE AST.
We found the array size expression is a floating expression,
such as
const int s = 10;
int a[s]; // 's' is a floating expression.
Could you tell me whether there are other places floating expresson may happen?
Thanks

**Comment by chunhualiao** [comment]
SgExpressions in types are not traversed by default.  They are still part of ROSE AST. 

You can try to find things in the whole dot graph dump of AST. 

There is a FAQ entry: 

https://en.wikibooks.org/wiki/ROSE_Compiler_Framework/FAQ#How_to_find_XYZ_in_AST?

We also have an online interface to generate such graphs for you
  http://demo.rosecompiler.org/getValues.html?tool=dotGeneratorWholeASTGraph

For your question. s is encoded as part of the SgArrayType, as shown at the left bottom of the screenshot of whole AST. 

![image](https://user-images.githubusercontent.com/1627206/67788162-0ec96f80-fa2f-11e9-95f8-4f4c7c4d8b10.png)

**Comment by seanchen1002** [comment]
besides SgArrayType, is there other place where floating expression happens?
-Sean

**Comment by chunhualiao** [comment]
Derived type nodes from SgType can have them also.  May I ask why do you concern about this so we can be more helfpul?

**Comment by seanchen1002** [comment]
We try to copy a function and its related sub functions, global variables and type declarations into a new file so we need to traverse all the expressions including floating expressions. Currently, we only find the floating expression on array size but we are not sure whether we miss something or not.
Thanks very much.
-Sean

**Comment by chunhualiao** [comment]
You should look at how transformations are done by the outliner
https://en.wikibooks.org/wiki/ROSE_Compiler_Framework/outliner

Looks like what  you want to do is very similar to what the outliner does, including copying things to another file, finding all dependent types , etc.

**Comment by seanchen1002** [comment]
Hi, Chunhua, Thanks.
I will take a look later.
-Sean
