### ISSUE TITLE
undefined reference to `XOMP_init' when using rose installed by apt-get

### ISSUE THREAD

**Issue by chunhualiao** [rose-compiler/rose#71]
Just record this issue here: 

I have installed rose compilers and tools using apt-get following the link https://github.com/rose-compiler/rose/wiki/Install-Using-apt-get.

Now, I am trying to translate an OpenMP program using the following command
 
identityTranslator -rose:openmp:lowering omp_pi_1.c
 
But I am getting the following errors.
 
Warning: OpenMP lowering is requested but no target runtime library is specified!
omp_pi_1.o: In function `main':
rose_omp_pi_1.c:(.text+0x32): undefined reference to `XOMP_init'
rose_omp_pi_1.c:(.text+0x9f): undefined reference to `XOMP_parallel_start'
rose_omp_pi_1.c:(.text+0xb0): undefined reference to `XOMP_parallel_end'
rose_omp_pi_1.c:(.text+0xeb): undefined reference to `XOMP_terminate'
omp_pi_1.o: In function `OUT__1__4645__':
rose_omp_pi_1.c:(.text+0x16a): undefined reference to `XOMP_loop_default'
rose_omp_pi_1.c:(.text+0x1df): undefined reference to `XOMP_atomic_start'
rose_omp_pi_1.c:(.text+0x1f9): undefined reference to `XOMP_atomic_end'
rose_omp_pi_1.c:(.text+0x1fe): undefined reference to `XOMP_barrier'
collect2: error: ld returned 1 exit status
 
It seems that identityTranslator can translate the OpenMP code and generate a threaded code named rose_omp_pi_1.c but it can't find "libxomp.h" header file.

**Comment by chunhualiao** [comment]
It looks like the ROSE configuration used to generate our Debian package does not include the OpenMP library path, 

solution:  add the OpenMP lib path into configure 

The configuration option needed is explained at: 
https://en.wikibooks.org/wiki/ROSE_Compiler_Framework/OpenMP_Support#Configuration

**Comment by pinnown** [comment]
I added support for OpenMP to the apt-get binary
