### ISSUE TITLE
Fail to change function return type by calling set_return_type(SgType *)

### ISSUE THREAD

**Issue by seanchen1002** [rose-compiler/rose#73]
Hi, 
I tried to change function return type but failed.
What I did now is as following:
from SgFunctionDeclaration to get its type, then from SgFunctionType to call set_return_type().
e.g.
SgFunctionDeclaration *func;
SgFunctionType *func_type = func->get_type();
func_type->set_return_type(new_return_type);
// after unparsing, return type of function 'func' was not changed as expected.

Thanks
-Sean

**Comment by chunhualiao** [comment]
There are defining and non-defining declarations for a function.

You may want to looked at the whole ast dot graph to understand their
existence and change the return types.

**Comment by seanchen1002** [comment]
Hi, Leo, thanks for your reply.
It seems that we cannot use set_return_type() to change the function return type directly.
Currently, in order to change the function return type, I will create a new SgFunctionType with new return type, then call SgFunctionDeclaration API  set_type() to achieve my goal.
Thanks.
-Sean

**Comment by seanchen1002** [comment]
> Hi, Leo, thanks for your reply.
> It seems that we cannot use set_return_type() to change the function return type directly.
> Currently, in order to change the function return type, I will create a new SgFunctionType with new return type, then call SgFunctionDeclaration API set_type() to achieve my goal.
> Thanks.
> -Sean

I found a easier way to change function return type by calling both set_return_type() and set_orig_return_type(). 
e.g.
`
SgFunctionDeclaration *func;
SgFunctionType *func_type = func->get_type();
func_type->set_return_type(new_return_type);
func_type->set_orig_return_type(new_return_type);
`
Be careful! It seems that function type is shared by multiple functions with the same type. As a result, the above code will change all the functions with the same type. If we wanted to only update a function, we had better create a new function type and set it into the function.
-Sean
