### ISSUE TITLE
what is difference between unparseToString() and unparseToCompleteString()?

### ISSUE THREAD

**Issue by seanchen1002** [rose-compiler/rose#74]
Hi, 
according to document, I am still confusing about the difference between the following two APIs.
std::string unparseToString () const
std::string unparseToCompleteString () const

How can I determine to use which one of them?

Besides, I found a strange issue.
When I use unparseToCompleteString () to unparse a AST node from a header file in the sub directory, it will return empty string.
e.g.
// include/x/t.h
typedef unsigned char pix_t;
// t.cpp
#include "t.h"

Thanks
-Sean

**Comment by mschordan** [comment]
From the documentation:
SgNode::unparseToCompleteString(): 
This function unparses the AST node (including comments and white space)
This function is a complement to the unparseToString() function and includes any associated comments and preprocessor control directives.

virtual std::string | unparseToString (SgUnparse_Info *info) const
This function unparses the AST node (excluding comments and unnecessary white space)

Comments:
In summary, "unparseToCompleteString' unparses the original source, whereas unparseToString strips off comments and unncessary white space (e.g. newline characters, etc.). unparseToString() will gives the source in one line, the string returned by unparseToCompleteString() may contain newline characters and when printed may span over multiple lines. These two functions are usually used in error messages of tools.
For source-to-source translation, unparsing an entire c or cpp file from the AST, the function SgProject::unparse or the global function backend(SgProject*) (which also compiles the generated code) should be used. Invoking either of those two functions generates a file rose_<originalFileName>.

**Comment by chunhualiao** [comment]
The doxygen doc has the info. 
http://rosecompiler.org/ROSE_HTML_Reference/classSgNode.html#a424645345b57be63499504a4ae3871e0

![image](https://user-images.githubusercontent.com/1627206/70104814-195dc280-15f4-11ea-8dfb-110b44a91dfc.png)

![image](https://user-images.githubusercontent.com/1627206/70104805-0ea32d80-15f4-11ea-94a3-18ae3c7513d9.png)
