### ISSUE TITLE
How to slice a program using rose?

### ISSUE THREAD

**Issue by coffezhou** [rose-compiler/rose#76]
I want to slice a program using rose, and I find that there are two directories related to slicing, namely,  proceduralSlicing and staticInterproceduralSlicing. However, there does not exist any successful examples that show how I can use the APIs. I try to build the test programs in the correspondding directories, but it fails. The APIs have been changed a lot after these test programs.

**Comment by ppete** [comment]
proceduralSlicing is deprecated and will be removed from ROSE.

staticInterproceduralSlicing is experimental and the code is currently not maintained. However, small test codes for it exist in 
  src/tests/nonsmoke/functional/roseTests/programAnalysisTests/staticInterproceduralSlicingTests .
  
Those tests should compile and run.
