### ISSUE TITLE
Rose failed to assertion when compile the example translator code

### ISSUE THREAD

**Issue by zhudalin** [rose-compiler/rose#79]
I installed Rose both in source code and apt install in ubuntu 18.04 (ubuntu-18.04.3-desktop-amd64), I can compile the common c++ code (The "Hello World!" code) normally, but failed to build the example translator code:
command line: rose-c++ -I../github/rose/install/include/rose test.cc

WARNING: Parent of non-real scope is not the first nondefining template. Reset!
rose-c++[19361] 57.39152s Rose[FATAL]: assertion failed:
rose-c++[19361] 57.39160s Rose[FATAL]:   /export/tmp.rose-mgr/jenkins/edg4x/workspace/development-edg-binary-RMC/COMPILER/gcc-7.4.0-default/EDGVERSION/5.0/src/frontend/CxxFrontend/EDG/edgRose/edgRose.C:54874
rose-c++[19361] 57.39164s Rose[FATAL]:   void EDG_ROSE_Translation::setup_duffs_device_switch_data(std::vector<a_statement*>&, std::vector<a_source_sequence_entry*>&, std::map<a_source_sequence_entry*, SgStatement*>&, std::vector<SgStatement*>&)
rose-c++[19361] 57.39167s Rose[FATAL]:   required: block_statement_map.find(*block_source_sequence_iterator) != block_statement_map.end()
Aborted (core dumped)

==============================================================
the example code: (which exist in https://github.com/rose-compiler/rose/wiki/How-to-create-a-translator)
// Example ROSE Translator: used for testing ROSE infrastructure

#include "rose.h"

int main( int argc, char * argv[] ) 
   {
  // Initialize and check compatibility. See Rose::initialize
     ROSE_INITIALIZE;

  // Build the AST used by ROSE
     SgProject* project = frontend(argc,argv);

  // Run internal consistency tests on AST
     AstTests::runAllTests(project);

  // Insert your own manipulation of the AST here...

  // Generate source code from AST and call the vendor's compiler
     return backend(project);
}

**Comment by pinnown** [comment]
When compiling ROSE tools like test.cc you need to use the compiler you used to compile ROSE (for the apt installation it was gcc-7 which is the default gcc on Ubuntu 18.04). rose-c++ is a rose tool that mimics a standard c++ compiler.

This specific error is because ROSE is currently incapable of compiling ROSE which is what this attempts to do.
