### ISSUE TITLE
ROSE crashes if label inserted in switch block

### ISSUE THREAD

**Issue by gary-bai** [rose-compiler/rose#80]
The reproducer:
```c
int yyparse()
{
  short yystate;
  short yyerrflag = 0;

yydefault:
  switch (yyerrflag) {
yyerrlab:
    case 1:;
    case 2:
      if (yystate >= 0) {
        goto yydefault;
      }
  }
}
```

> created CFGNode with illegal index:
> index = 1 while max index is:0
> Error: node = 0x7f6f7e6b90a8 = SgLabelStatement
> 
> ///////////// begin of SageInterface::dumpInfo() ///////////////
> --------------base info. for SgNode---------------
> 0x7f6f7e6b90a8 SgLabelStatement
> ...
> ///////////// end of SageInterface::dumpInfo() ///////////////
> ../../../../../src/frontend/SageIII/virtualCFG/virtualCFG.C:40: VirtualCFG::CFGNode::CFGNode(SgNode*, unsigned int): Assertion `false' failed.
> 

> /curr/software/rose/lib/librose.so.0(_ZN10VirtualCFG7CFGNodeC2EP6SgNodej+0x129)[0x7f6f8fb8f049]
> /curr/software/rose/lib/librose.so.0(+0x20c5b2c)[0x7f6f8fb75b2c]
> /curr/software/rose/lib/librose.so.0(_ZN16SgCaseOptionStmt11cfgOutEdgesEj+0x38)[0x7f6f8fb7aa08]
> /curr/software/rose/lib/librose.so.0(_ZNK10VirtualCFG7CFGNode8outEdgesEv+0x1b)[0x7f6f8fb8edeb]
> /curr/software/rose/lib/librose.so.0(_ZN10VirtualCFG11MakeClosureISt19const_mem_fun_ref_tISt6vectorINS_7CFGEdgeESaIS3_EENS_7CFGNodeEES1_IS6_NS_7CFGPathEE11IsDFAFilterPFS8_RKS8_SC_ENS_15FilteredCFGEdgeISA_EEE2goESC_+0x16b)[0x7f6f8fb4adeb]
> /curr/software/rose/lib/librose.so.0(_ZN10VirtualCFG11MakeClosureISt19const_mem_fun_ref_tISt6vectorINS_7CFGEdgeESaIS3_EENS_7CFGNodeEES1_IS6_NS_7CFGPathEE11IsDFAFilterPFS8_RKS8_SC_ENS_15FilteredCFGEdgeISA_EEE2goESC_+0x242)[0x7f6f8fb4aec2]
> /curr/software/rose/lib/librose.so.0(_ZNK10VirtualCFG15FilteredCFGNodeI11IsDFAFilterE8outEdgesEv+0x241)[0x7f6f8fb4b711]

**Comment by chunhualiao** [comment]
We are phasing out virtualCFG and don't have resources to fix bugs of it. We are setting up better analysis but it will take some time.
