### ISSUE TITLE
AST outlining on a SgBasicBlock followed by SageInterface::copyStatement on the outlined function produces an inconsistent AST

### ISSUE THREAD

**Issue by forflo** [rose-compiler/rose#81]
Hi everyone!

in this [bug reproduction package](https://github.com/forflo/bugReproductionPackage04) I reproduce a bug that shows that AST outlining and AST deep copy are currently not composable for every input.

In isolation, both AST deep copy and AST outlining work as expected and leave the AST in an consistent state (measured with `AstTests::runAllTests`). However, when used in conjunction with each other, they leave the AST in an _inconsistent_ state!

# Case 1

Let's take a input that conceptually looks like this:

`func A() { ...; S; ... }`

Then let's call ROSE's AST outliner on `S`. This will produce:

`func A() { ...; OUT_S(); ... }   OUT_S() { S; }`

Running `AstTests::runAllTests()` before and after the outlining shows that everything is alright. :heavy_check_mark: 

# Case 2

Let there be the same input:

`func A() { ...; S; ... }`

Again, let's call the outliner. The result is:

`func A() { ...; OUT_S(); ... }   OUT_S() { S; }`

Now, in addition to that, let's also try to clone the function `OUT_S` as demonstrated in `tests/nonsmoke/functional/roseTests/astInterfaceTests/deepCopy.C`. We roughly do (take the details from [the reproduction package](https://github.com/forflo/bugReproductionPackage04/blob/master/input_succeeding_clone.c):

```c++
SgFunctionDelcaration *d = SageInterface::findDeclarationStatement<SgFunctionDeclaration>(..., "OUT_S", ...);
SgFunctionDeclaration cloned_d = isSgFunctionDeclaration(SageInterface::copyStatement(d));
cloned_d->set_name("OUT_S_2");
SageInterface::appendStatement(cloned_d, ...);
```

This should leave us with an AST like this one:

`func A() { ...; OUT_S(); ... }   OUT_S() { S; }  OUT_S_2() { S; }`

Unparsing on this AST works without a problem. However, `AstTests::runAllTests` now terminates the program with precisely the following error output on stdout :x: :

```
@@@@ SgFunctionParameterList
@@@@ foop__
@@@@ 
Error: initializedName->get_symbol_from_symbol_table() == NULL initializedName = 0x7fbb7ea8bb78 = foop__ 
Inside of Sg_File_Info::display(Error: initializedName->get_symbol_from_symbol_table() == NULL) of this pointer = 0x556863d50810 
     isTransformation                      = true (part of a transformation) 
     isCompilerGenerated                   = false 
     isOutputInCodeGeneration              = true (output in code generator) 
     isShared                              = false 
     isFrontendSpecific                    = false 
     isSourcePositionUnavailableInFrontend = false 
     isCommentOrDirective                  = false 
     isToken                               = false 
     isDefaultArgument                     = false 
     isImplicitCast                        = false 
filename and line, column info should be invalid for transformation or compiler generated objects
we print their values anyway for your reference
     filename = transformation 
     line     = 0  column = 0 
     physical_file_id       = -3 = transformation 
     physical_line          = 0 
     source_sequence_number = 0 
Inside of Sg_File_Info::display(Error: initializedName->get_symbol_from_symbol_table() == NULL: locatedNodeParent) of this pointer = 0x556863d50730 
     isTransformation                      = true (part of a transformation) 
     isCompilerGenerated                   = false 
     isOutputInCodeGeneration              = true (output in code generator) 
     isShared                              = false 
     isFrontendSpecific                    = false 
     isSourcePositionUnavailableInFrontend = false 
     isCommentOrDirective                  = false 
     isToken                               = false 
     isDefaultArgument                     = false 
     isImplicitCast                        = false 
filename and line, column info should be invalid for transformation or compiler generated objects
we print their values anyway for your reference
     filename = transformation 
     line     = 0  column = 0 
     physical_file_id       = -3 = transformation 
     physical_line          = 0 
     source_sequence_number = 0 
In TestAstSymbolTables::visit(): output the symbol tables for the scope = 0x7fbb7e8793a0 = SgBasicBlock 
Printing out the data within the symbol table (p_table = 0x556863d56b60,label = default settings size = 0): 
Internal static data: p_no_name: true p_name =  
Symbol table has parent = 0x7fbb7e8793a0 = SgBasicBlock 
failing_clone: /home/florian/A_rose/rose_repo/src/midend/astDiagnostics/AstConsistencyTests.C:3192: virtual void TestAstSymbolTables::visit(SgNode*): Assertion `local_symbol != NULL' failed.
```

# What I found out so far

- `initializedName->get_symbol_from_symbol_table()` does does not give us a reference to the symbol of the initialized name.
- `get_symbol_from_symbol_table` calls `find_symbol_from_declaration`
- `find_symbol_from_declaration` calls `SgSymbolTable::find` on the scope the initName sits in
   - and [find](https://github.com/rose-compiler/rose/blob/1dad28fcca68217331befa833826263d0f8f618d/src/ROSETTA/Grammar/Support.code#L8172) then [iterates](https://github.com/rose-compiler/rose/blob/1dad28fcca68217331befa833826263d0f8f618d/src/ROSETTA/Grammar/Support.code#L8200) over all the symbols and for each symbol `S` tries to get the symbol base using `get_symbol_basis`.yt
    - [get_symbol_basis](https://github.com/rose-compiler/rose/blob/1dad28fcca68217331befa833826263d0f8f618d/src/ROSETTA/Grammar/Support.code#L8203) returns a non-null pointer `P`
    - then inside the iteration a branch [checks](https://github.com/rose-compiler/rose/blob/1dad28fcca68217331befa833826263d0f8f618d/src/ROSETTA/Grammar/Support.code#L8216) whether `P == initializedName`
    - this fails and SgSymbolTable::find returns NULL which then fails an assertion in  `TestAstSymbolTables::visit`

I can only assume but it looks as though, the symbol table is simply not deeply copied in this case.

However I do not understand why this error only occurs if you chain the Outliner _and_ a deepCopy. 

Please help me, I'm stuck here.

Kind regards

**Comment by chunhualiao** [comment]
I tested it using a latest version of ROSE and I don't see any error message. 

 ./rose-compiler --version

ROSE (version: 0.10.0.11)

My slightly improved reproducer is:

https://github.com/chunhualiao/bugReproductionPackage04

I will close this issue for now unless I hear something different.
