### ISSUE TITLE
pragma not in AST if template function definition

### ISSUE THREAD

**Issue by huhanvictory** [rose-compiler/rose#85]
Example C++ code:
void test1() {
    #pragma HLS LOOP_TRIPCOUNT min=100 max=100
    int n = 1;
}
template <int SIZE2>
void test2() {
    #pragma HLS LOOP_TRIPCOUNT min=100 max=100
    int m = 1;
}

1. the pragma is not in AST if function is template function definition(EX. test2)
2. the pragma is in AST if function is normal function definition(EX. test1)

Is it possible, we can add pragma to AST if template function definition?

**Comment by tristanvdb** [comment]
Unfortunately the C/C++ frontend that we are using does not provide this information. We will soon update to the latest version of that frontend. If that update does not fix this issue will be looking at other solutions.
This is only an issue if you want to transform the template as the pragma will be present in the AST of all instantiations of the function (which are generated by the frontend).

I am closing the issue as it is a known issue which we will address in our (on-going) effort to enable transformations on template declaration.
