### ISSUE TITLE
ROSE Compiler : EDG binary tarball is not available

### ISSUE THREAD

**Issue by yogitanegi** [rose-compiler/rose#88]
Hi All,

I am getting following errors while installing ROSE compiler(since yesterday).

Downloading EDG binary tarball: roseBinaryEDG-4-9-x86_64-pc-linux-gnu-gnu-8.3-4.82daf656b47602afa41dc38d5a30fa107fbc1e7b.tar.gz
error: the EDG binary tarball is not available (or the web site is not reachable).
Please contact rose-public@nersc.gov to troubleshoot this error.
make[5]: *** [EDG.tar.gz] Error 1
make[5]: Leaving directory `/home/apps/capc-1.0/ROSE_BUILD/src/frontend/CxxFrontend'
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory `/home/apps/capc-1.0/ROSE_BUILD/src/frontend/CxxFrontend'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory `/home/apps/capc-1.0/ROSE_BUILD/src/frontend'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/apps/capc-1.0/ROSE_BUILD/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/apps/capc-1.0/ROSE_BUILD'
make: *** [all] Error 2

Any help in this regard would be highly appreciated.

Thanks,
Yogita

**Comment by pinnown** [comment]
What ROSE version number are you using? 

Based on what I can figure out from the EDG signature the ROSE version you are using did not have EDG binaries generated for gnu 8, only binaries up to gnu 5 were generated. ROSE version 0.9.12.0 and later do have EDG binaries for gnu 8 but ROSE does not yet have full compatibility. Currently gnu 7 is the latest we fully support.

**Comment by yogitanegi** [comment]
I am using ROSE version 0.9.10.54 and GCC version 8.3

**Comment by pinnown** [comment]
That ROSE did not have binaries generated for GCC 8 and only went to GCC 5.

We are in the process of adding support for GCC 8 but new binaries will not be generated for older versions of ROSE. You will need to switch compiler to continue using ROSE.

**Comment by yogitanegi** [comment]
Okay. I got it. 
Thanks for the reply :+1:
