### ISSUE TITLE
Python binding

### ISSUE THREAD

**Issue by abitrolly** [rose-compiler/rose#89]
I am looking for a tools that can help me automate transforming T-SQL syntax from MS SQL to different database. ROSE can probably help with that. Only writing C code for the tool is too hardcore for me. Maybe there are Python bindings?

**Comment by charlesareynolds** [comment]
There are no Python bindings, sorry.  ROSE tools must be written in C++.  Try this:
[https://www.google.com/search?q=c%2B%2B+for+python+programmer](url)
