### ISSUE TITLE
How to get the function declaration with definition from a function call efficiently?

### ISSUE THREAD

**Issue by seanchen1002** [rose-compiler/rose#92]
Hi,  we tried to use getAssociatedFunctionDeclaration() to get the function declaration. But the result has no definition. We also tried to use SgDeclarationStatement::get_definingDeclaration () to get its related declaration with definition but we meet the issue#91. Currently, we need to check all the function declarations with definition to find the matched one, which is time-consuming. Do you have more efficient and reliable method to get the function declaration with definition from a function call?
Thanks
-Sean

**Comment by chunhualiao** [comment]
Sean, we may have FAQ entry for your question: 
https://github.com/rose-compiler/rose/wiki/FAQ#how-to-find-xyz-in-ast

The right method is to view the whole graph AST to find information visually first. Then use access functions (get_xxx() based on labels of edges in the AST graph) to get a function symbol from a function call expression, then from the symbol to a function declaration, then a declaration to a definining declaration.

**Comment by chunhualiao** [comment]
For example, the following code has an AST graph in pdf (attached)
```
void foo();

void bar()
{
   foo();
}


You should find in the pdf the chain of nodes from a call site to its function definition: SgFunctionCallExp  -->SgFunctionRefExp -> SgFunctionSymbol --> ... 

You then call a chain of access functions to reach the node you want to get. 

[test-20200219_001233-30860_WholeAST.pdf](https://github.com/rose-compiler/rose/files/4222441/test-20200219_001233-30860_WholeAST.pdf)


```

**Comment by seanchen1002** [comment]
Hi, @chunhualiao  thanks for your reply. Currently, we cannot use the your suggested way to look for the defined declaration because of issue#91. Instead, we need to traverse all the AST and apply intensive matching check to make sure we get the correct result, which is time consuming.
Thanks
-Sean

**Comment by chunhualiao** [comment]
https://github.com/rose-compiler/rose/issues/91 should have closed this issue.  Please let us know if it is not the case.
