### ISSUE TITLE
Newer Boost versions

### ISSUE THREAD

**Issue by hbrunie** [rose-compiler/rose#96]
Same issue as Newer Boost versions #84.
I re-open here because it has been closed.
The issue I encountered is with BOOST 1_70_0.

**Comment by pinnown** [comment]
ROSE is not currently compatible with any boost 1_68_0 and later when using c/c++.

**Comment by pinnown** [comment]
As of ROSE version 0.9.13.93 the changes needed for support newer boost versions have been added. Currently it is blacklisted so configure needs to be run with the --disable-blacklist flag. The blacklisting will be removed after additional testing in the coming few weeks as part of the next major release process.

**Comment by pinnown** [comment]
ROSE version 0.10.0.0 is now compatible with boost 1_70_0.
