### ISSUE TITLE
ROSE frontend crash

### ISSUE THREAD

**Issue by seanchen1002** [rose-compiler/rose#98]
When I try to compile two C++ files with a header file,  latest ROSE frontend crashed but the previous version works.
Please change file t.h.txt into t.h, file t1.cpp.txt into t1.cpp and file t2.cpp.txt into t2.cpp.
$ROSE_frontend   t1.cpp t2.cpp

The expected error is as following:

mars_opt_org[1124] 4.73439s Rose[FATAL]: assertion failed:
mars_opt_org[1124] 4.73450s Rose[FATAL]:   /export/tmp.rose-mgr/jenkins/edg4x/workspace/development-edg-binary-RMC/COMPIL
ER/gcc-4.9.4-default/EDGVERSION/5.0/src/frontend/CxxFrontend/EDG/edgRose/edgRose.C:39075
mars_opt_org[1124] 4.73454s Rose[FATAL]:   SgFunctionDeclaration* EDG_ROSE_Translation::convert_routine_prototype(a_routi
ne_ptr, bool, a_template_ptr)
mars_opt_org[1124] 4.73457s Rose[FATAL]:   required: declstmt_parent->get_firstNondefiningDeclaration() == decl->get_firs
tNondefiningDeclaration() || declstmt_parent->get_firstNondefiningDeclaration() == first_nondefining_declaration
Print backtrace:
mars_opt_org[0x48071e]
/lib64/libc.so.6(+0x36340)[0x7fb4f632c340]
/lib64/libc.so.6(gsignal+0x37)[0x7fb4f632c2c7]
/lib64/libc.so.6(abort+0x148)[0x7fb4f632d9b8]
/local/youxiang/rose/install_orig_debug/lib/librose.so.0(+0x2710769)[0x7fb4fc043769]
/local/youxiang/rose/install_orig_debug/lib/librose.so.0(_ZN6Sawyer6Assert4failEPKcS2_RKSsS2_jS2_+0xf8)[0x7fb4fc05d598]
/local/youxiang/rose/install_orig_debug/lib/librose.so.0(_ZN20EDG_ROSE_Translation25convert_routine_prototypeEP9a_routine
bP10a_template+0x29ef)[0x7fb4fb9aedff]
/local/youxiang/rose/install_orig_debug/lib/librose.so.0(_ZN20EDG_ROSE_Translation26convert_template_prototypeEP10a_templ
ate+0x4e2)[0x7fb4fb9a8aa2]
/local/youxiang/rose/install_orig_debug/lib/librose.so.0(_ZN20EDG_ROSE_Translation27parse_secondary_declarationER18Source
SequenceList+0x59)[0x7fb4fb9e5079]
/local/youxiang/rose/install_orig_debug/lib/librose.so.0(_ZN20EDG_ROSE_Translation38parse_global_or_namespace_scope_entit

[t.h.txt](https://github.com/rose-compiler/rose/files/4441535/t.h.txt)
[t1.cpp.txt](https://github.com/rose-compiler/rose/files/4441536/t1.cpp.txt)
[t2.cpp.txt](https://github.com/rose-compiler/rose/files/4441537/t2.cpp.txt)

**Comment by seanchen1002** [comment]
We try to upgrade ROSE library but the above issue has blocked us from upgrading. It is critical for us.
Thanks
-Sean

**Comment by tristanvdb** [comment]
I cannot reproduce this issue using ROSE v0.10.0.30 with gcc 4.9 (centos 7).

**Comment by seanchen1002** [comment]
Thanks for your quick reply. I just try the latest release branch (0.9.130). Let me try v0.10.0.30 again.
-Sean

**Comment by seanchen1002** [comment]
Fantastic! v0.10.0.30 can pass. After rerunning regression test, we found other minor issues. My colleague and I will file them later. Thanks again.
-Sean
