### ISSUE TITLE
Assertion `associatedStatement != __null' failed

### ISSUE THREAD

**Issue by gary-bai** [rose-compiler/rose#99]
Reproducer:
```cpp
class A {
public:
    A() {}
    operator bool() {
        return false;
    }
};

void k()
{
    A a;
    if (A a2 = a) {
        ;
    }
}
```
When setting the name of `a2` via a call to
```cpp
void SageInterface::set_name(SgInitializedName*, SgName)
```
program crashes:
```
program: ../../../../../src/src/frontend/SageIII/sageInterface/sageInterface.C:1245: virtual void SageInterface::set_name(SgInitializedName*, SgName)::RoseVisitor::visit(SgNode*): Assertion `associatedStatement != __null' failed.
```

**Comment by gary-bai** [comment]
Affected version: rose-0.10.0.30

**Comment by seanchen1002** [comment]
After debugging, there are some variable reference for 'a' in the memory pool. 
I have applied the following patch in my local to work around it.

src/frontend/SageIII/sageInterface/sageInterface.C
`@@ -1231,10 +1242,12 @@ SageInterface::set_name ( SgInitializedName *initializedNameNode, SgName new_nam

                       // DQ (11/13/2018): Mark the statement associated with this SgVarRefExp (see test9 in UnparseHeade
                          SgStatement* associatedStatement = getEnclosingStatement(varRefExp);
-                         ROSE_ASSERT(associatedStatement != NULL);

                       // DQ (11/13/2018): Mark the statement associated with this SgVarRefExp (see test9 in UnparseHeade
                          SgStatement* associatedStatement = getEnclosingStatement(varRefExp);
-                         ROSE_ASSERT(associatedStatement != NULL);
-                      // associatedStatement->set_isModified(true);
-                      // associatedStatement->set_containsTransformation(true);
-                         associatedStatement->setTransformation();
+                         //ROSE_ASSERT(associatedStatement != NULL);
+                         if (associatedStatement != NULL) {
+                           // associatedStatement->set_isModified(true);
+                           // associatedStatement->set_containsTransformation(true);
+                           associatedStatement->setTransformation();
+                         }
`

**Comment by tristanvdb** [comment]
I have a slightly different patch that will hopefully make it to the next weekly release (sunday night).

FYI: we only have to set the SgVarRefExp as transformation. This is used for token-based unparsing, which only unparses transformed code (the rest come from original file).

**Comment by tristanvdb** [comment]
It was integrated in v0.10.2.2
